rubygems/bundler-site

- source/layouts/blog_layout.haml
Turns this:
Into this:
This solution was proposed in this issue: https://github.com/middleman/middleman-syntax/issues/16
> Fix code indentation in blog posts

- README.md
- source/v1.9/bundle_update.haml
On the bundle update command page, it can be observed that some of the content from the command block and some text below it leaks into the side bar causing the text to clash. This pull request aligns the text properly.
> Fix content extending into the side bar

- source/v1.10/bundle_install.haml
It wasn't clear to me that `--deployment` is also meant to be used for CI environments. This PR makes it clear and also explains a bit more what `--deployment` is doing.
> Explain that install --deployment is also suitable for CI

- source/blog/2015-06-24-version-1-10-released.html.markdown
Upon reading the post, this piece confused me. `fixes definitely fix` read as 2 verbs instead of a noun, then verb. Using a different word helps clear this up to my mind.
Thanks!
> Fix confusing language in version 1.10 release post

- source/partials/_sidebar.haml
- source/v1.10/bundle_gem.haml
- source/v1.10/index.haml
`bundle gem` is the de-facto standard for creating rubygem projects, but this is not readily apparent by reading the current bundler.io site. This PR adds a section to the homepage explaining the `bundle gem` command, and improves the existing documentation.
> Improve the documentation for `bundle gem` and surface it on the homepage

- config.rb
- source/layouts/base.haml
- source/layouts/blog_layout.haml
- source/layouts/layout.haml
- source/partials/_head.haml
- source/partials/_header.haml
Highlights:
- Add markdown extention for features not available in standard markdown  
- Set partial directory for easy referencing. ie. `partial 'partials/header' to partial 'header'
- Create a base layout which all other layouts inherit from.
> Markdown extentions, set partials_dir, create base layout

- source/layouts/blog_layout.haml
- source/layouts/layout.haml
- source/v1.10/index.haml
- Simple solution to haml adding indentation to `pre` blocks from markdown files. 
For an illustration of this, have a look at the code block on the "Report a bug" page on the bundler website. Every line after the first additional indentation. The solution above is mentioned here: http://stackoverflow.com/questions/16605840/multiline-code-block-in-markdown-adds-unwanted-tabs
- Add paragraph tags to block of text on index page
> Haml pre block indentation fix and add paragraph tags to blocks of text

- source/layouts/blog_layout.haml
- source/stylesheets/_normalize.css
- source/stylesheets/application.scss
- Remove `find_and_preserve` because `~` does the same thing
- Add normalize.css for cross-browser consistency and changes to footer css code
> Remove redundant find_and_preserve, add normalize.css and minor stylesheet changes

- source/v1.10/git.haml
Hello,
I know that the `submodules` option for getting gems via git is documented in the [Gemfile manual](http://bundler.io/man/gemfile.5.html), but I think it would be nice to mention it in the [git page](http://bundler.io/git.html).
Also, I looked it up and it seems this feature exists since the 1.0 version, but I was not sure if I should change older docs. Can I add this info in the older docs too? I'd update this PR.
Thanks
> Show the submodules option in the git page

- source/v1.0/gemfile.haml
- source/v1.1/gemfile.haml
- source/v1.10/gemfile.haml
- source/v1.2/gemfile.haml
- source/v1.3/gemfile.haml
- source/v1.5/gemfile.haml
- source/v1.6/gemfile.haml
- source/v1.7/gemfile.haml
- source/v1.8/gemfile.haml
- source/v1.9/gemfile.haml
I guess somewhere the anchor changed from [`#pessimistic_version_constraint`][1] to [`#pessimistic-version-constraint`][2]. This fixes all the links.
[1]: http://guides.rubygems.org/patterns/#pessimistic_version_constraint
[2]: http://guides.rubygems.org/patterns/#pessimistic-version-constraint
> Fix anchor in links to RubyGems version specifiers page

- source/v1.10/gemfile.haml
- source/v1.11/gemfile.haml
- source/v1.3/gemfile.haml
- source/v1.5/gemfile.haml
- source/v1.6/gemfile.haml
- source/v1.9/gemfile.haml
I'm not a native English speaking person, but AFAIK "an" article is used in preference to "a" one when it goes before vowel letters or sounds. At least, my tongue stumbled when I passed that place while reading documentation. :)
Hope, this PR will be helpful.
> Fix typo of 'a' article before vowels

- source/partials/_footer.haml
- source/stylesheets/application.scss
* 'forkme' image makes Firefox/Chrome display a warning
* In the case of the font, it is not being loaded by Firefox/Chrome given it is
considered as active (not passive) mixed content
> Fixes mixed content warning/blocking when https

- source/blog/2016-04-28-the-new-index-format-fastly-and-bundler-1-12.md
- source/v1.12/whats_new.haml
- The flag is called `--patch` for targeting the third semver portion via `bundle outdated`: bundler/bundler#4312
> Correct `--tiny` flag to `--patch` flag for `bundle outdated`

- source/shared/_whats_new.haml
- source/v1.12/whats_new.haml
> Add version 1.12 link to shared "what's new" banner

- Rakefile
- This caveat is not clear from the script and failure to enter in the correct credentials at this point in the deploy script can result in multiple commits being pushed in the eventual deploy.
> Warn about two factor auth and tokens for password input in site deploy rake task

- source/contributors.html.haml
- source/stylesheets/_hexagon_image.scss
I noticed that the contributors page wasn't rendering correctly in
Safari on my iPhone -- the first team member's face/name show ups, and
then after that there is only white, no other team members or footer.
I think the issue is that there are multiple, conflicting strategies for
"clipping" the profile photos into hexagons, and there's some kind of
clash there.
With this change, the page renders correctly for Safari and Chrome. On
Firefox, the page will render, but it no longer has hexagon-clipped
profile photos. According to http://bennettfeely.com/clippy/ the
clip-path property doesn't work in Firefox, although the previous
implementation did manage to get it working by embedding an svg in the
HTML and then loading that.
IMO losing the hexagon-clipping on Firefox is worth it for the …
> Fix contributors page rendering for Safari

- source/contributors.html.haml
It works for me in Firefox (v47 and v49), Safari i Chrome.
Fixes error on Firefox from #223
> Readd html clipPath in Team page only for Firefox

- source/v1.12/index.html.md
‘/v1.12#getting-started’ url has been updated to include the ability to join the slack channel. Also the IRC link has been removed and former non functioning links have been replaced with now working links. 
Please follow the /v1.12#getting-started url and scroll down to the 'Get Involved' section at the bottom to see changes.
> the static sites ‘Getting Involved’ section of the

- source/v1.12/bundle_outdated.html.md
Adds documentation for the `--major` `--minor` `--patch` and `--parseable` options that were added to the `outdated` utility in v1.12. Closes #217 
I noticed that @kruczjak converted all the docs to markdown in #230 - I can make a branch off that PR if you want to merge in the markdown conversion first.
> updated documentation for outdated utility

- source/v1.12/bundle_outdated.html.md
Fix small typo in `bundle outdated` documentation with version 1.12
> Fix typo in bundle outdated in 1.12

- source/v1.12/deploying.html.md
- source/v1.13/deploying.html.haml
Aims to fix the broken `Learn More: Packing`links on http://bundler.io/deploying.html and https://bundler.io/v1.12/deploying.html
> Fix broken links to "Learn More: Packing"

- source/issues.html.md
- source/localizable/v1.13/guides/creating_gem.en.html.md
- source/localizable/v1.13/guides/creating_gem.pl.html.md
- source/localizable/v1.13/guides/using_bundler_in_application.en.html.md
- source/localizable/v1.13/guides/using_bundler_in_application.pl.html.md
- source/v1.13/git.html.haml
Throughout the website the use of some example commands are denoted with a `$` while other examples are not denoted. This PR is making the use of the denotation consistent throughout the site.
Let me know what you think.
Thanks!
> Make command line usage denotation consistent

- source/v1.13/git_bisect.html.md
The git bisect page which is [mentioned here](http://bundler.io/v1.13/guides/using_bundler_in_application.html) is currently missing, resulting in a page not found. This PR adds the missing page to the current source.
Thanks.
> Add git bisect page to v1.13

- source/localizable/index.html.haml
- source/v1.13/bundler_workflow.html.haml
- source/v1.13/gemfile.html.haml
- source/v1.13/index.html.haml
On the home page and several other pages there are examples of Gemfiles like:
```
source 'https://rubygems.org'
gem 'nokogiri'
gem 'rack', '~>1.1'
gem 'rspec', :require => 'spec'
```
This does not work, RSpec have removed `spec` since this documentation was written.
```
/Users/c/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require': cannot load such file -- spec (LoadError)
from /Users/c/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
from /Users/c/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
from /Users/c/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
from /Users/c/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
from …
```
> remove require: spec, and update rack version where mentioned

- source/v1.12/bundle_install.html.haml
- source/v1.13/bundle_install.html.haml
(theoretically) closes #271
Two important things:
1. I combed through the `CHANGELOG` for v1.12 and 1.13 and didn't see any major changes to the options provided to `bundle install` - correct me if this is wrong! I copied the file over from v1.11
2. Running this locally, I can't for the life of me figure out what's going on with the urls and the files being served and how to configure that locally. I'm assuming this *just works* ™️ when the pages are actually served. If there's a config I need to set somewhere, let me know and I'll get the `README` for this repo updated to reflect 👌
> copy missing bundle install pages

- source/v1.13/git.html.haml
This PR cleans up the Using Git documentation. Changes include:
- Added paragraph spacing where appropriate
- Rework content to be more clear and remove redundant sentences
- Use gems that can actually be installed via git (nokogiri has no gemfile and cannot be installed without the version)
- Remove extra padding on code/usage examples
- Deep merge repo no longer exists, use nokogiri instead as example gem with no .gemfile
- action_pack & active_model have been renamed to actionpack and activemodel
- fix git source example with ref, branch, tag options
Thanks.
> cleanup git documentation on latest version

- Gemfile
- Gemfile.lock
- config.rb
it is apparently unmaintained, and because it triggers a full reload for
every single html file anytime any html file is changed, our site causes
it to get stuck livereloading every single file D:
> remove livereload

- helpers/guides_helper.rb
Selecting a guide in the sidebar whilst currently reading another guide would result in a page not found. Closes #314.
This issue appears to be have been introduced in https://github.com/bundler/bundler-site/commit/5f1163c9ea2b98fe37dbd15aac989173ba77c38b where middleman was updated to a newer release.
In the guides helper, it's generating the paths to guides like `v1.15/guides/using_bundler_in_applications`. This used to have been made into an absolute path by Middleman but this no longer appears to be the case.
Prefix the guide URLs with a forward slash to force an absolute path instead of being relative
> prefix `/` to guides URL to force an abolsute path

- source/v1.15/bundler_setup.html.haml
- source/v1.15/faq.html.haml
- source/v1.15/gemfile.html.haml
- source/v1.15/groups.html.haml
- source/v1.15/rails.html.haml
- source/v1.15/rubygems.html.haml
- source/v1.15/updating_gems.html.haml
This PR is just removing the extra padding at the bottom of code examples that still have them
> remove excess padding in code/command examples

- source/v1.14/git_bisect.html.md
- I saw there was no background explanation of the `git bisect`command in the "How to `git bisect` in projects using Bundler" docs guide.
- I added a new section at the beginning of the "How to `git bisect` in projects using Bundler" guide background information about what `git bisect` does.
My fix...
- I wrote up an introductory explanation of `git bisect`, and linked to the official git documentation, as well as to a Thoughtbot blog post that guides the user on how exactly to use `git bisect` with examples.
- I thought this guide in particular would be less intimidating to anyone who is not …
> Add git bisect explanation to "How to git bisect in projects using Bundler" guide

- lib/tasks/versions.rake
- lib/templates/whats_new.html.haml.erb
- source/blog/2017-05-19-bundler-1-15-bundle-oh-so-fast.html.markdown
- source/v1.14/whats_new.html.haml
- source/v1.15/whats_new.html.haml
The localized sources were missed for version 1.15, leading to 404s on guides. It seems good to create a task that makes sure guides will be available for new versions. 👍
> Rake task to create new minor version

- source/layouts/_navbar.haml
I think the link in footer is not easily accessible.
> Add repository link in header

- helpers/guides_helper.rb
Currently the guides are not being linked correctly in the sidebar and the `guides` helper is breaking in development due calling a method on `nil`
Clicking any link to the a guide in the sidebar does not go the intended page. And going to `docs.html` would break in development.
Remove `nil`s in the guides helper and remove the extra `/` in the guides url helper.
> Fixing guides helper and guides url helper

- source/stylesheets/application.css.scss
I came across this extra space on [What's New in each Release for v1.15](http://bundler.io/v1.15/whats_new.html)
- I think there was some problem with Bootstrap styles.
My fix...
- The pseudo `:after` element on the `.row` class caught my eye. I tinkered around, wrote over a default Boostrap style, and came up with this fix.
- Now, it should hopefully look like this:
- It's a quick fix to solve the spacing issue 
- Closes #325
> Get rid of unnecessary extra spacing on What's New in each Release page

- source/v1.12/whats_new.html.haml
- There was a duplicate header for Bundler's "What's New in Each Release" v1.12 update. 
- To get rid of it
My fix...
- Delete the unnecessary header.
- Resolves Issue #326
> Remove duplicate header in What's New post

- source/v1.12/whats_new.html.haml
- While reading through the "What's New in V1.12" of Bundler blog post, I noticed there was a broken link and some missing markup. 
It looked like this:
- I guess markdown syntax doesn't work in the `haml` blog post files. 
My fix...
- I added in vanilla HTML into the `haml` blog post file to add in the markup and fix the broken link.
- It should look like this, now:
- to improve the user's experience on the bundler.io site ✨
> Fix broken link in 'What's New in v1.12'

- .travis.yml
These are now provided via the Travis web API, and had to be updated
because the API key in question changed.
> Remove Fastly env vars

- source/v1.15/index.html.haml
In the index page, there is a broken link and also two markdown style links which do not render those link properly.
This commit changes those to `haml` link helper and it also fixes the bundler setup guides path, which was changed in `v1.15`.
> Fix broken links for index page in v1.15

- source/localizable/index.html.haml
In the homepage the `How Does Bundler Work?` link is pointing to the getting started guide from `v1.12` instead of using the current version.
This commit fixes this and it also replaces the hardcoded version number with the `current_version`, so in the future, we don't have to update it manually.
> Fix link for the current getting started guide

- source/v1.15/index.html.haml
In the `/v1.15` page, we have a section called `Use Bundler with`, where we have some links that were intended to point to the guides. But unfortunately, those links are broken and still seems to point to the old html file that does not exist anymore
This commit fixes those links and points those broken link to the correct guide path that changed in PR #322.
> Fix broken links in the doc index page

- source/v1.15/guides/deploying.html.haml
In the `Deploying bundled applications` (Link: `/guides/deploying.html`) guide, there seems to be a broken link, the `executables` does not seems to be linking to the correct path. And, the guide also using a sample from the old Heroku's way of adding the configuration.
This commit fixes that link to the correct path, and it also updates the Heroku sample to their latest way of configuring environment variable.
Ref: https://devcenter.heroku.com/articles/bundler
> Minor updates on the deploying guide

- source/localizable/v1.15/guides/using_bundler_in_applications.en.html.md
In the `Using Bundler In Applications` guide, the `git bisect` link seems to be broken.
This commit updates the link to the correct guide path.
Ref: https://bundler.io/v1.15/guides/using_bundler_in_applications.html#troubleshooting
> Fix a broken link in using bundler guide

- source/v1.16/gemfile.html.haml
Broken links during move from /groups.html to /guides/groups.html (between 1.14 and 1.15)
> Fix broken links to guides/groups.html

- data/contributors.yml
- lib/tasks/man_generator/man.rake
The problem was the `.ronn` files need `index.txt` to be present to properly link things.
Closes https://github.com/bundler/bundler/pull/6143
My diagnosis was we needed to build `index.txt` for 1.16+
> [Man] Ensure index.txt is built for 1.16+

- locales/en.yml
- locales/es.yml
- locales/pl.yml
- source/localizable/index.html.haml
- source/localizable/v1.15/guides/bundler_setup.es.html.haml
- Bundler.io should be localized into Spanish. 
- I translated one of Bundler's guides into Spanish. 
My fix...
- I translated the "Bundler Setup" guide into Spanish.
- I feel software is very English-centric. This is a step forwards towards making Bundler more friendly to non-English speakers 👌🏼
> Localize Bundler Setup Guide in Spanish

- source/v1.12/git_bisect.html.md
- source/v1.13/git_bisect.html.md
- source/v1.14/git_bisect.html.md
- source/v1.15/guides/git_bisect.html.md
- source/v1.16/guides/git_bisect.html.md
/bin/bash can be misleading for instance on macs using `brew install bash` and rvm, since it will point to the factory bash.
In general, scripts are considered more portable using  the shebang with `!#/usr/bin/env bash`.
More info: https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash
May I also note that this ** PR is now consistent with all other script files in the repository** 👍 (I am a big fan of consistency)
> update bash shebang to '/usr/bin/env bash' form

- config.rb
- source/compatibility.html.haml
- source/conduct.html.md
- source/contributors.html.haml
- source/older_versions.html.haml
- source/sponsors.html.haml
- source/stylesheets/_search.scss
- Like @lynncyrin noted in Issue #254, not all pages come up in Bundler.io's search. 
Specifically, the missing pages that should be searchable but currently weren't include:
- `compatibility.html`
- `conduct.html`
- `contributors.html`
- `older_versions.html`
My fix...
- I read through [the documentation for the Middleman search gem](https://github.com/manastech/middleman-search) that bundler.io uses and found out that in order to make a page searchable, we need to both give the page [frontmatter](https://middlemanapp.com/basics/frontmatter/) (the YAML at the top of the page), and append it to the `search.resources` array …
> Enable missing pages to be searchable

- source/v1.12/bundler_setup.html.md
- source/v1.16/rationale.html.haml
- There were some outdated references in the Bundler rationale and setup guide docs that referred to how to use the require directive for `rack/cache`.
- After reading the discussion on https://github.com/bundler/bundler-site/issues/130, I edited out the require directive for `rack/cache`since it's not needed anymore.
My fix...
- Edit out outdated documentation.
- it's what was discussed in issue https://github.com/bundler/bundler-site/issues/130
> Edit out require directive for rack/cache in docs

- locales/en.yml
- locales/es.yml
- locales/pl.yml
- source/localizable/index.html.haml
I realized the homepage didn't have a prominent link to the reference docs, so I added one. I also added a prominent link to join the Slack, as well as restoring the final paragraph of the old homepage with a call for readers to get involved and contribute.
> Add homepage action buttons

- source/v1.16/gemfile.html.haml
This commit adds an example that's consistent with this page:
https://github.com/bundler/bundler-site/blob/master/source/v1.16/rationale.html.haml
Previously, there was no example of what the documentation was describing.
If this PR looks good, I can update it to include updated documentation for other versions besides 1.16 also. Let me know!
> Add missing example for 'require' specification

- source/localizable/v1.16/guides/creating_gem.en.html.md
- source/localizable/v1.16/guides/using_bundler_in_applications.en.html.md
- source/v1.16/guides/bundler_setup.html.haml
The problem was inconsistency in formatting titles. These three guides were accidentally left out from the updates made in PR https://github.com/bundler/bundler-site/pull/360
My diagnosis was to fix headers for the guides on creating a Ruby gem, managing app dependencies, and the using Bundler with Ruby guides.
My fix was to edit the titles as follows:
1. **Developing a RubyGem using Bundler** is now **How to create a Ruby gem with Bundler**
2. **Using Bundler in Applications** is now **How to manage application dependencies with Bundler**
3. Swapped out **Bundler.setup** with **How to use Bundler with Ruby** at the top of the page.
I chose this fix because it …
> Updated titles for three guides

- README.md
- source/v1.16/gemfile.html.haml
When on the gemfile page, there is a link to learn more on using gems hosted via git. When clicked
I received a 404
The relative link reference was missing the `guide` in the path
I updated the link, and fixed one other small typo.
> Fix 404 to guides/git

- source/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
These changes include a single-line command that will run the automated SSL troubleshooting script even on windows in a command prompt, and update the instructions for manually downloading and installing the latest rubygems to be a bit clearer.
> Update SSL steps to work on Windows

- source/v1.16/guides/git.html.haml
I initially logged Issue #372 for this, so just copying what part of what I said in there:
> Recently I needed to install a gem from a Git repository, but the gem was nested within a subdirectory of the repository. Looking at the [existing docs](http://bundler.io/guides/git.html) I couldn't find anything that would allow me to do this. I eventually found an issue that mentioned the `glob` parameter and it worked, but it would be nice if this was documented more explicitly.
Just an option that's missing from the existing git installation documentation.
Added a short blurb to the documentation to make this option more discoverable for folks. 😄 
Not sure how you all choose what gems to use as examples. I just put down the one I needed to discover to use `:glob` for to install.
Open to any …
> Document git :glob option for installing gems from subdirectories

- source/v1.16/bundle_viz.html.haml
(see https://github.com/bundler/bundler/issues/6527)
---
Documentation mismatched with the usage and online help in bunder viz
My diagnosis was that `-r` is used for `--retry` and the correct `--requirements` flag is `-R` which is not reflected on the site.
Documentation modification to match the behaviour.
> Correct --requirements flag.

- source/v1.16/guides/bundler_in_a_single_file_ruby_script.html.md
The example of using Bundler in a single-file Ruby script https://bundler.io/v1.16/guides/bundler_in_a_single_file_ruby_script.html fails with 
```
>ruby bundler_inline_example.rb
Gems installed and loaded!
Traceback (most recent call last):
bundler_inline_example.rb:11:in `<main>': uninitialized constant Nap (NameError)
```
`nap` gem has no `Nap` namespace currently. It has its `VERSION` constant in `REST` module.
Use the correct namespace. 
¯\\_(ツ)_/¯
> Fixed the example of using Bundler in a single-file Ruby script

- source/v1.16/guides/bundler_docker_guide.html.md
closes #386 
Per #386:
> Based on bundler/bundler#6524, it looks like the Docker default images for Ruby have cleverly engineered a situation where only one bundle and one application can exist inside the docker container.
> For users who want to have more than one Gemfile, or simply install gems via RubyGems and use them as system gems, this situation is confusing, and has historically led to a lot of bug reports and even pull request against Bundler.
> Instead, we want to document how Bundler handles binstubs, document how the default Docker Ruby image handles binstubs, and then document how the user can configure Bundler within Docker to …
> Created "how to use Bundler with Docker guide"

- source/v1.16/guides/groups.html.haml
Closes #393 
As noted in #393, the only place in our documentation that contained information about optional groups was the v1.10 release notes. It was recommended that we add it to the "How to manage groups of gems" section, which this PR does.
Exact language that was added:
> Mark a group as optional using <code>group :name, optional: true do</code>, and then opt
into installing an optional group with <code>bundle install --with name</code>.
Tested locally and the page renders correctly with the added section.
> Adding optional groups section to docs

- source/v1.16/guides/git.html.haml
The git guide uses hash rocket style syntax. This PR updates to the standard hash syntax that pretty much everyone is using these days.
> Update git guide to standard hash syntax

- source/blog/2019-01-03-announcing-bundler-2.html.markdown
I've removed a small typo in the Heroku buildpack section.
I've also corrected the link to the issues guide at the bottom of the post.
> Fixed two typos in Bundler 2 release post

- source/v2.0/guides/bundler_2_upgrade.html.md
There is a paragraph in the Bundler 2 upgrade that talks about the Gemfile.lock formatting being changed. This change was pushed back to Bundler 3.
> fix note about Bundler 2 lockfile being formatted slightly different

- source/v2.0/guides/bundler_2_upgrade.html.md
The problem was that "How to upgrade to Bundler 2" document made users to misunderstand RubyGems requirement at minimum. 
Indeed, in bundler v2.0.0, the requirement was v3.0.0 at minimum.
However, since bundler v2.0.1, the requirement was relaxed to v2.5.0 from v3.0.0.
ref : https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html
None
My fix is changing RubyGems requirement to v2.5.0 from v3.0.0 in "How to Upgrade to Bundler 2" document.
None
> Change RubyGems requirement to v2.5.0 from v3.0.0 at minimum

- source/compatibility.html.haml
https://bundler.io/compatibility.html should have a note that Bundler 2.0 requires Ruby 2.3.0
> REQUIRED RUBY-VERSION:
> &gt;= 2.3.0
> REQUIRED RUBYGEMS VERSION:
> &gt;= 3.0.0
source: https://rubygems.org/gems/bundler/versions/2.0.0
`gem install bundler # on older ruby version`
ERROR:  Error installing bundler:
bundler requires Ruby version >= 2.3.0.
New Bundler version requires Ruby 2.3.0
The problem was incomplete documentation.
My fix was `gem install bundler --version '< 2'`
> add note: Bundler 2.0 requires Ruby 2.3.0

- source/v2.0/guides/bundler_2_upgrade.html.md
The problem was that the section name `BUNDLED_WITH` isn't actually a section in a Bundler lockfile.
My diagnosis was that this should have said `BUNDLED WITH`.
My fix was to change `BUNDLED_WITH` to `BUNDLED WITH`.
I chose this fix because it's clearly what was intended.
> Fix 'BUNDLED_WITH' -> 'BUNDLED WITH'

- source/v2.0/guides/bundler_2_upgrade.html.md
Heroku now supports Bundler 2 with the official Ruby buildpack, so the documentation can now reflect this.
> Heroku now supports Bundler 2

- source/v2.0/guides/bundler_2_upgrade.html.md
*  That there's useless cats in the documentation
* That it's a semantics change that would make the documentation look better
My fix...
* Is to remove the cats and only use grep
* It's the most common way to solve cat pipes to grep
> Remove useless cat

- source/v1.16/rationale.html.haml
The code comment could previously suggest that `bundle` is a shortcut of `bundle install` **within the command** `bundle install`.
It can be confusing to the user.
Clarify that `bundle` on its own is a shortcut of `bundle install`. Of course, please correct me if I'm wrong.
Also, let me know if the proposed code comment is too long for the snippet, and should be broken down into two lines or rephrased.
> Clarify a sentence in rationale.html.haml

- source/blog/2019-05-14-solutions-for-cant-find-gem-bundler-with-executable-bundle.html.markdown
Readers might incorrectly copy the command and try to execute `run`.
> Fix blog command syntax highlighting

- source/v2.0/guides/git.html.haml
The problem was that this example was pointing nokogiri to rack, pretty sure that's not right.
The URLs have been updated.  
Seemed most logical
> Docs(gems-from-git page): Fix incorrect URLs for nokogiri

- source/layouts/commands_layout.haml
- source/layouts/md_guides_layout.haml
The problem was that Google is showing bundler docs for old versions in search results. An example of this problem is pointed out by @indirect in the 3rd bullet point of https://github.com/rubygems/bundler/pull/7591#discussion_r369845718.
My diagnosis was that we already have a solution for this, namely, consider the latest version of each page as the canonical version.
The problem, I think, is that the regexp for adding the canonical link was incorrect for the kind of pages referenced by @indirect.
My fix is to use a proper regexp that includes all the pages where we want to do this. While fixing it, I also noticed other pages where we also want to do this that were using a different layout.
I chose this fix because it should improve our docs visibility in search results.
> Fix canonical linking

- source/v2.0/guides/faq.html.haml
- source/v2.0/rubygems.html.haml
The problem was that the information about the reasons to commit your `Gemfile.lock` could be deepened and clarified.
My diagnosis was that we should expand on the reasons. Also, I noticed that we're not mentioning the roles on `Gemfile` and `Gemfile.lock` files inside gems, which is something not very well known.
My fix is to try to clarify the reasons for committing `Gemfile.lock` by default, and also to add a specific question about the roles of `Gemfile` and `Gemfile.lock` inside gems.
> Expand FAQs about Gemfile and Gemfile.lock usage in libraries

- README.md
- source/layouts/_navbar.haml
The problem was that the links at the Bundler site were pointing only to the [legacy Bundler repository](https://github.com/rubygems/bundler).
Responsive design is supported as well:
Thanks for your support and guidance.
Best regards,
David Auza
> Update repository links

- Gemfile.lock
The problem was as a developer, I'd get a change in the Gemfile after `bundle install`.
My diagnosis was that this could be a problem for the bundle install `--deployment` flag, which forbids changes to the lockfile on installing.
A recent update to the Ruby version used made this change necessary. See #509
My fix was to check in the current version of the lockfile.
I chose this fix because I couldn't come up with any alternative.
> chore: Update Gemfile.lock to reflect Ruby 2.6.6p146

- README.md
- helpers/docs_helper.rb
- lib/tasks/release.rake
- lib/tasks/travis/deploy.rake
- source/blog/2016-07-10-bundler-1-13-and-redesigned-bundler-io.html.markdown
- source/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
- source/v1.17/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
- source/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
While investigating a Heroku deploy problem, I noted that the Travis deploy script and other things refer to the previous GitHub Organisation.
Example of Git output:
https://travis-ci.org/github/rubygems/bundler-site/builds/672651835#L2986
```
git add -A .
git config user.name 'Travis CI'
git config user.email '[secure]'
git commit -m 'bundler/bundler-site@d5ae0760c9f18f91ee4589291fe0398f0fe82f0b'
[master f9ca89d8] bundler/bundler-site@d5ae0760c9f18f91ee4589291fe0398f0fe82f0b
2 files changed, 7 insertions(+), 7 deletions(-)
git push origin master
remote: This repository moved. Please use the new location:        
remote:   git@github.com:rubygems/bundler.github.io.git        
To github.com:bundler/bundler.github.io
efb71573..f9ca89d8  master -> master
```
This repo has been moved to the …
> chore: Refer to rubygems GitHub Organisation, not bundler

- data/known_plugins.yml
- lib/tasks/regenerate_known_plugins_yml.rake
See #505 - there is no **Known Plugins** page in the site. Users have no way of discovering the community's Plugins for Bundler.
#505 calls for a regeneratable YAML data-set for Middleman, kept up-to-date with a Rake task.
The generated YAML file could be checked in to git. (The Issue calls for this, too.)
❓ **Wondering:**
Most of the gems named with a prefix `bundler-` are not using the `plugins.rb` way of extending Bundler, but the "add a CLI command" way.
This PR currently adds data for `plugins.rb`-using gems, only. I'm wondering if you think I should add fewer skips.
This PR adds a YAML file from which it's easy to add a page. Compare to the Contributors page. Note: this PR does not include adding a page, only fetching the data for one.
My fix was "use some curl and grep" from the …
> Add data/known_plugins.yml and its Rake task

- source/v2.0/guides/git.html.haml
[DEPRECATED] Using the `config` command without a subcommand [list, get, set, unset] is deprecated and will be removed in the future. Use `bundle config set local.gem_name /foo/bar/baz.git` instead.
The problem was that docs are out of sync with the current version of bundler.
Running the commands as given in the README gives a deprecation error.
Update the docs
It is good.
> Update bundle config syntax to non-deprecated version

- source/layouts/_footer.haml
- source/layouts/_navbar.haml
The problem was trying to navigate to the bundler via the "Repository" link in the https://bundler.io/ navbar. 
My diagnosis was the link was incorrect in the navbar, as it was correct in the footer.
My fix is to update the link, as well as update the footer to the new `rubygems/bundler` home.
I chose this fix because I think the users want to go to the bundler github site, not the rubygems site, from https://bundler.io/
> Update navbar Repository link to bundler

- source/v2.0/guides/git.html.haml
The problem was that I couldn't easily glean a key precondition to using the Local Git Repository feature, which resulted in spending several minutes trying to use the feature before realizing that I was doing it incorrectly.
My diagnosis was that a key piece of information was buried a few paragraphs down and difficult to spot until I read the documentation a few times.
My fix draws the reader's attention to this key piece of information.
I chose this fix because it seems like the smallest change to the existing documentation that could possibly provide value to the reader, helping them avoid my mistake.
> Highlighted a key precondition to use the Local Git Repository feature.

- source/v2.1/gemfile.html.haml
I saw the example `Gemfile` on the main website, which uses a global `source` command, clicked on "Learn more", just to learn that global `source` commands are strongly discouraged for good reasons.
The main website violated best practices, so it probably hasn't received much attention over the last weeks or months.
Adjust the example to the best practices.
The alternative would be to change the recommendation on the Gemfile description site, but the reasons provided for discouraging global `source` commands are very convincing.
> Adjust example Gemfile to best practices

- .github/workflows/build.yml
- .travis.yml
- Gemfile.lock
- helpers/docs_helper.rb
- source/partials/_commands_sidebar.haml
- source/v1.12/deploying.html.md
- source/v1.12/docs.html.haml
- source/v1.13/deploying.html.haml
- source/v1.13/docs.html.haml
- source/v1.14/deploying.html.haml
- source/v1.14/docs.html.haml
- source/v1.15/docs.html.haml
- source/v1.15/guides/deploying.html.haml
- source/v1.16/docs.html.haml
- source/v1.16/guides/deploying.html.haml
- source/v1.17/docs.html.haml
- source/v1.17/guides/deploying.html.haml
- source/v2.0/docs.html.haml
- source/v2.0/guides/deploying.html.haml
- source/v2.1/docs.html.haml
- source/v2.1/guides/deploying.html.haml
In https://github.com/rubygems/rubygems/pull/3921, in order to be able to remove txt versions on man pages, the ronn sources are being renamed to keep the man section in their name. So, before they'd be named `bundle-<command>.ronn`, and now they are named `bundle-<command>.1.ronn`.
This PR changes the documentation site to catch up with that change.
While at it, I also updated the "BUNDLED WITH" section in the lockfile and also fixed some broken links pointing to `bundle-package` man pages, that are now `bundle-cache`
> Catch up with man page naming change in main rubygems/rubygems repo

- source/v1.10/bundle_console.html.haml
- source/v1.11/bundle_console.html.haml
- source/v1.13/bundle_console.html.haml
- source/v1.14/bundle_console.html.haml
- source/v1.15/bundle_console.html.haml
- source/v1.16/bundle_console.html.haml
- source/v1.17/bundle_console.html.haml
- source/v1.6/bundle_console.html.haml
- source/v1.7/bundle_console.html.haml
- source/v1.8/bundle_console.html.haml
- source/v1.9/bundle_console.html.haml
- source/v2.0/bundle_console.html.haml
- source/v2.1/bundle_console.html.haml
https://bundler.io/bundle_console.html
https://bundler.io/v2.1/bundle_console.html
Removes an extra empty line from bundler console.
I chose this fix because formatting should be consistent with other pages.
> Remove an extra empty line from bundler console

- source/blog/2019-05-14-solutions-for-cant-find-gem-bundler-with-executable-bundle.html.markdown
We get a constant flow of opened issues from OS-ruby users about the recommended solution for this error, `gem update --system`, not working. We can't really do anything about these errors because upgrading rubygems via `gem update --system` is not really supported for OS-ruby installations, since we're not in control of the ruby code OS packagers add to their custom ruby build.
My diagnosis was that the solution is not the best we can recommend. Installing the exact bundler version in the `Gemfile.lock` file is a better solution, and will work for everyone.
My fix is to reorder and reword the blog post to be more useful and to reduce the flow of incoming issues mentioning this (apparently well positioned) blog post.
I chose this fix because it will fix things for users without adding …
> Reword blog post to troubleshoot an error to be more useful

- .travis.yml
I noted we were using not-latest version in the CI configuration (which we are moving away from).
My diagnosis was the version was 1 patch behind latest.
My fix was to use 2.2.5, latest.
This change was just to keep up-to-date, I don't know of any changes in Bundler that we rely on.
> CI: Use Bundler 2.2.5

- source/v1.16/guides/bundler_plugins.html.haml
- source/v1.17/guides/bundler_plugins.html.haml
- source/v2.0/guides/bundler_plugins.html.haml
- source/v2.1/guides/bundler_plugins.html.haml
- source/v2.2/guides/bundler_plugins.html.haml
The [instructions from Bundler's docs](https://bundler.io/v2.0/guides/bundler_plugins.html#running_your_plugin_locally) for `Running your plugin locally...` didn't work for me:
```
$ bundler plugin install my_plugin --source file://Users/me/Code/my_plugin/
Fetching source index from file://Users/me/Code/my_plugin/
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from file://Users/me/Code/my_plugin/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from file://Users/me/Code/my_plugin/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from file://Users/me/Code/my_plugin/
Could not fetch specs from file://Users/me/Code/my_plugin/
```
[Here's an example](https://github.com/bundler/bundler/issues/5445#issuecomm …
> Fix the command for "Running your plugin locally"

- Gemfile.lock
The problem was that gihub alerted us of a security issue in the kramdown dependency.
My fix is to upgrade kramdown.
> Bump kramdown to fix security issue

- source/v2.1/bundle_plugin.html.haml
- source/v2.2/bundle_plugin.html.haml
The link should be `.html`, not `.html.haml`
The problem was the link in https://bundler.io/v2.2/bundle_plugin.html was broken.
My diagnosis was the link is `.html.haml`.
My fix is to remove `.haml` part from the link.
I chose this fix because other working links end with `.html`, not `.html.haml`.
> Fix a broken link on plugin page

- source/v2.2/guides/git.html.haml
The example for `gist:` sources in the [Git Guide](https://bundler.io/v2.2/guides/git.html) was for a `git:` source instead.
n/a
Replace it with a `gist:` example.
n/a
> Fix an example in Git Guide

- source/v2.2/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
Related: https://github.com/rubygems/bundler-site/pull/541
current link returns 404.
> Update GlobalSignRootCA cert link

- source/localizable/index.html.haml
- source/v2.2/index.html.haml
I made the change in the index file and in the v2.2
The problem was that the links were pointing to the old repo.
My diagnosis was we needed to update them to current ones.
My fix is to point to the README in the rubygems/rubygems repo.
I chose this fix – fixing the source file and the latest generated version's HTML, since it was quick to do, and not too onerous to review.
Also: this is a focused change, which does not do All The Things.
> Update the Contributing link to the new URI

- source/v2.2/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
As mentioned in #540, existing .pem files might exist in subdirectories rather than in the ssl_certs directory directly.
I was unsure, if the difference (subdirectory or not) is, because I have a linux system rather than Windows/macOS. But as the macOs description is otherwise identical to the linux workflow I did choose to not add extra steps
Fixes #540
> Windows: Add a hint for possible subdirectories for ssl_certs

- source/blog/2021-02-15-a-more-secure-bundler-we-fixed-our-source-priorities.html.markdown
The problem was since we have finally released a fix, the blog post about dependency confusion issues is out of date again.
My fix is to update the blog post again and pray this problem is gone for good now.
> Second tweak to dependency confusion blog post

- source/v2.2/guides/groups.html.haml
`Bundler.setup` documentation doesn't make it clear that only the first call to `Bundler.setup` is effective and that in particular, any `Bundler.setup` calls inside a `bundle exec` context will be ineffective, because `bundle exec` already calls `Bundler.setup`. In addition to this, the documentation mentions deprecated flags.
My fix is to rewrite documentation to fix the above issues.
Closes #577.
> Clarify `Bundler.setup` docs

- .github/workflows/build.yml
- .github/workflows/deploy.yml
The problem was very minor: CI looked like it did 2 `bundle install` actions.
My diagnosis was that we could use ruby/setup-ruby's `bundler-cache: true` and only that.
My fix was to remove the extra bundle install step. And then to document the `bundler-cache: true` setting in all places used.
I chose this fix because I wanted speed and clarity configuration.
> build: Document bundler-cache, and rely on it

- Gemfile
- Gemfile.lock
The problem was nothing. Just that the middleman version was pinned in #552 so we were not able to get dependency updates from dependabot. Some vulnerable dependency was introduced in #552 (but fixed in #562 later).
n/a
My fix is to upgrade activesupport from 5.2 to 6.1 to fully use Ruby 3.0.
To simplify dependencies.
> Update middleman 4.3.11+patches to 4.4.0

- Gemfile.lock
A warning when booting the app
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
```
`bundle update thor`.
> bundle update thor

- README.md
A link to GitHub in README.md is now dead due to rubygems/rubygems#3921 since 2020-09-04
- https://github.com/rubygems/rubygems/pull/3921
Just fix it.
Apart from this, links from each man page will be fixed in:
- https://github.com/rubygems/bundler-site/pull/615
> Fix dead links to GitHub on README.md

- source/localizable/index.html.haml
A link to CLI docs from https://bundler.io/ is changed from https://bundler.io/man/bundle-install.1.html to https://bundler.io/v2.3/man/bundle-install.1.html
The link changed is pointed as follows:
> Fix link to CLI docs with the latest one

- source/blog/2018-08-10-july-bundler-update.html.markdown
- source/blog/2018-09-10-august-bundler-update.html.markdown
- source/blog/2018-10-15-september-monthly-update.html.markdown
- source/blog/2018-10-25-announcing-bundler-1-17-0.html.markdown
- source/blog/2018-11-04-an-update-on-bundler-2.html.markdown
- source/blog/2018-11-05-october-monthly-update.html.markdown
- source/blog/2018-12-08-november-monthly-update.html.markdown
- source/blog/2019-01-03-announcing-bundler-2.html.markdown
- source/blog/2019-01-04-an-update-on-the-bundler-2-release.html.markdown
- source/blog/2019-02-02-december-monthly-update.html.markdown
- source/blog/2019-03-12-january-february-bimonthly-update.html.markdown
- source/blog/2019-05-14-solutions-for-cant-find-gem-bundler-with-executable-bundle.html.markdown
- source/blog/2020-04-27-march-monthly-update.html.markdown
`date` should be `YYYY/MM/DD`, `YYYY-MM-DD anything`, or omitted. Otherwise title will miss.
Closes #621
Currently `date` field is `YYYY-MM-DD` (no time and no timezone, which is redundant with date in the filename, so we can remove them.
> Remove redundant date from frontmatters in blog

- helpers/docs_helper.rb
Dead links to source Git happen on both for v2.3 and earlier man pages.
Example:
https://bundler.io/v2.3/man/bundle-install.1.html has a link entitled as "Edit this document on GitHub" to `https://github.com/rubygems/rubygems/blob/master/bundler/man/bundle-install.1.ronn`, which is dead.
This regression has happened since 2020-09-04 with https://github.com/rubygems/rubygems/pull/3921.
A solution for this problem was not included in #542.
Fixes the dead links on GitHub from man pages from the current version of Bundler (2.3 as of writing).
Removes the dead links on GitHub from man pages from the non-current version of Bundler (1.12 through 2.2 as of writing). Instead of that, the link to the latest version's man is added there.
~~An end-user (website reader) should be able to consider if …
> Fix dead links on GitHub from man pages

- README.md
Middleman does not accept `-h` but `--bind-address`.
```
$ bundle exec middleman --help
Usage:
middleman middleman:cli:server
Options:
-e, [--environment=ENVIRONMENT]                                  
-p, [--port=PORT]                                                
[--server-name=SERVER_NAME]                                  # The server name of preview server
[--bind-address=BIND_ADDRESS]                                # The bind address of the preview server
[--verbose], [--no-verbose]                                  # Print debug messages
[--instrument], [--no-instrument]                            # Print instrument messages
[--profile], [--no-profile]                                  # Generate profiling report for server startup
-d, [--daemon], [--no-daemon] …
```
> Fix wrong options for Middleman

- config.rb
The problem was one page redirect was incorrect, as per https://github.com/rubygems/bundler-site/pull/624#issuecomment-1176017733.
My fix is to add the missing `guides/` part to the target URL.
> Fix incorrect redirection

- source/localizable/v2.3/guides/bundler_setup.es.html.haml
- source/localizable/v2.3/guides/bundler_sharing.es.html.haml
The problem was these guides were not updated in recent versions.
My fix to adapt the changes applied to the English guides to these translated guides, so they are available to at https://bundler.io/es/v2.3/guides/bundler_setup.html and https://bundler.io/es/v2.3/guides/bundler_setup.html
and https://bundler.io/es/v2.3/guides/bundler_sharing.html.
```diff
--- source/localizable/v1.15/guides/bundler_setup.es.html.haml	2022-07-06 11:16:59.000000000 +0200
+++ source/localizable/v2.3/guides/bundler_setup.es.html.haml	2022-07-06 11:17:30.000000000 +0200
@@ -3,7 +3,7 @@
---
.container.guide
-  %h2 Configurando Bundler
+  %h2 Cómo usar Bundler con Ruby
.contents
.bullet
@@ -96,7 +96,7 @@
source 'https://rubygems.org'
gem 'rails', '5.0.0'
-          gem 'rack-cache', :require => 'rack/cache'
+ …
```
> Update Spanish guides to catch up with latest changes

- README.md
To run `npm install` in the development setup instruction is not included and the server looks running when `bundle exec middleman server` is executed even without webpack installed.
A novice contributor can set up the environment for development. `npx webpack` dismisses the warning.
Just show it in the instruction.
Documentation is now but automation would be the next step.
> npm install is required to setup dev env

- .gitpod.Dockerfile
- .gitpod.yml
- README.md
The contribution guide has not been coded so hard for a new contributor to get started to contributions to the repository.
Gitpod (cloud edition) is helpful since everyone can use a workspace on it for 50 hours / months.
Added `.gitpod.yml` but there is no pre-built image including Ruby 3.1 and Node.js so we need to prepare it by ourselves.
1. Visit `https://github.com/tnir/bundler-site/tree/gitpod` and click a button to launch a Gitpod workspace for this.
2. First build will take some time (5 minutes and more).
Added a button to launch from README.md for novice contributors. I can do it for GitHub Codespaces as well in another PR.
> Add .gitpod.yml to make dev env easier

- README.md
`rake man` causes an error if you run it as shown in README.md:
```
$ rake man
git fetch
git fetch
rm -rf source/v1.12/man
mkdir -p source/v1.12/man
git reset --hard HEAD
HEAD is now at e86410c3 Version 1.12.6 with changelog
git checkout origin/1-12-stable
HEAD is now at e86410c3 Version 1.12.6 with changelog
/.../.rvm/rubies/ruby-3.1.2/bin/ruby -S ronn -5 man/*.ronn
/.../.rvm/rubies/ruby-3.1.2/bin/ruby: No such file or directory -- ronn (LoadError)
rake aborted!
Command failed with status (1): [/.../.rvm/rubies/ruby-3.1.2/bin/ru...]
lib/tasks/man_generator/man.rake:22:in `block (3 levels) in <top (required)>'
lib/tasks/man_generator/man.rake:19:in `chdir'
lib/tasks/man_generator/man.rake:19:in `block (2 levels) in <top (required)>'
lib/tasks/man_generator/man.rake:3:in `each' …
```
> Use Bundler on raken man

- .rubocop.yml
- Rakefile
- config.ru
- helpers/command_reference_helper.rb
- lib/tasks/ci/deploy.rake
- lib/tasks/ci/ssh_repo.rake
- lib/tasks/man_generator/man.rake
- lib/tasks/release.rake
- lib/tasks/vendor_files.rake
Rocket hashes are used in Ruby code.
They can be replaced with new ones.
Replace rocket hashes in Ruby code with Ruby 1.9 ones.
Simplified code would give a better contributor experience.
No other cops are not enabled in this PR as per the title.
> Replace rocket hashes with Ruby 1.9 ones

- assets/javascripts/anchors.js
- assets/javascripts/commands_layout.js
An end-user has loaded unused jQuery.
- See also #653
These code currently depending on jQuery can be replaced with vanilla JS.
The relevant code was simply replaced with vanilla JS.
Just follow the instruction from AnchorJS: https://github.com/bryanbraun/anchorjs/blob/master/README.md
HTMLs for command references were done from ones for search with Lunr.
> Remove jQuery dependency from commands layout

- config.rb
The problem was moving around urls at #651 broke search for guides content.
My diagnosis was that after moving guides to not be version dependent, their contents are no longer indexed.
My fix is to add the new urls to the list of search resources.
> Restore search for guides content

- assets/javascripts/search_arrows.js
An end-user has loaded unused jQuery.
- See also #653
- cf. #654
These code currently depending on jQuery can be replaced with vanilla JS.
The relevant code was simply replaced with vanilla JS.
It was planned that `search_arrows.js` is replaced without jQuery along with `search.js`, but it was found difficult as `search.js` has Popper.js v1 dependency.
> Remove jQuery dependency from search_arrows

- source/sitemap.xml.builder
While bunder.io fully supports HTTPS, `/sitemap.xml` has only `http`-based URLs.
We can simply replace them with HTTPS.
Use `https` over `http` as protocol.
No other choice.
> Use https over http in sitemap.xml

- assets/stylesheets/_sidebar.scss
- source/layouts/commands_layout.haml
- source/layouts/md_guides_layout.haml
An end-user downloads duplicated HTML and CSS parts for sidebar via their browser.
We can get rid of either of them.
Remove the bottom one and make the other fully responsive along with Bootstrap 4 (#644).
> Remove duplicated code for sidebar

- assets/javascripts/search_arrows.js
An end-user cannot input Enter to visit the selected page on search after #664 due to the regression in it.
- #664
To get rid of jQuery from this JS was incomplete.
Completely remove jQuery methods.
Needed to fix a regression...
> Allow users to put enter on search

- package-lock.json
- package.json
- webpack.config.js
`imports-loader` is not required for `bootstrap@4` or did not look required for `bootstrap-sass`.
We need to follow up #562. Commit message in #562 explains:
> * `imports-loader` to inject the code to make jquery globals available into bootstrap-sass.
Just remove use of imports-loader and dependency of it.
While I am not sure if Bootstrap 3 (or bootstrap-sass) requires it, it is obvious there is no reference to imports-loader after #644.
> Remove imports-loader as it is now not required

- assets/javascripts/application.js
- assets/javascripts/search.js
- assets/stylesheets/_bootstrap-overrides.scss
- assets/stylesheets/_guide.scss
- assets/stylesheets/_opacity.scss
- assets/stylesheets/application.css.scss
- package-lock.json
- package.json
- source/contributors.html.haml
- source/layouts/_navbar.haml
- source/layouts/base.haml
- source/layouts/commands_layout.haml
- source/layouts/guides_layout.haml
- source/layouts/md_guides_layout.haml
- source/localizable/index.html.haml
- source/partials/_blog_header.haml
- source/partials/_commands_sidebar.haml
- source/v1.12/docs.html.haml
- source/v1.13/docs.html.haml
- source/v1.14/docs.html.haml
- source/v1.15/docs.html.haml
- source/v1.16/docs.html.haml
- source/v1.17/docs.html.haml
- source/v2.0/docs.html.haml
- source/v2.1/docs.html.haml
- source/v2.2/docs.html.haml
- source/v2.3/docs.html.haml
Maybe nothing.
Closes #673
- Previous update: #644
Newer library might cause faster page rendering.
- Update Bootstrap from 4.6.1 to 5.1.3.
- `.row` classnames were removed at a bare minimum.
Bootstrap 4.6 would be EOL'd sometime in the near future.
> Bump Bootstrap from 4.6.1 to 5.1.3

- config.rb
- source/v1.12/docs.html.haml
- source/v1.13/docs.html.haml
- source/v1.14/docs.html.haml
/older_versions.html is no more useful to end-users.
Closes #686
Removal and redirection look better.
The file was removed and `/older_versions.html` will be redirected to `/whats_new.html`.
> Remove orphan /older_versions.html

- assets/javascripts/search.js
An end-user has loaded unused jQuery.
- See also #653
- cf. #654 and #664
These code currently depending on jQuery can be replaced with vanilla JS.
The relevant code was simply replaced with vanilla JS.
It was found difficult as `search.js` has Popper.js v1 dependency.
- Blocked by #644
- Blocked by #681
> Remove jQuery dependency from search

- package-lock.json
- package.json
node-sass (LibSass) has been deprecated.
sass (Dart Sass) is the active package.
> We highly recommend using [Dart Sass](https://github.com/sass/dart-sass).
> -- https://github.com/webpack-contrib/sass-loader/blob/997f3eb41d86dd00d5fa49c395a1aeb41573108c/README.md
Replace node-sass with sass.
webpack build (`npx webpack -d source-map --progress --color`) gets slow 2x times (from 1700-2000ms to 3900-4400ms on my local).
`fibers` package is not recommended for Node.js 16+, so I guess we cannot use it any more.
> Fibers is not compatible with Node.js v16.0.0 or later. Unfortunately, v8 commit [dacc2fee0f](https://github.com/v8/v8/commit/dacc2fee0f815823782a7e432c79c2a7767a4765) is a breaking change and workarounds are non-trivial. ([see introduction to …
> Replace node-sass with sass (Dart Sass)

- source/layouts/_navbar.haml
2 extra HTTP requests happen after #644:
- CSS (11 kB) `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css`
- Font (79 kB) `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/webfonts/fa-solid-900.woff2`
Closes #696
We can replace the element (`%i.fa.fa-search`) and asset loads (CSS and Font; ~ 90 kB in total) with an in-place SVG element (~ 0.7kB).
- Removes the element (`%i.fa.fa-search`)
- Removes the asset load (`https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css`)
- Adds an in-place SVG element adapted from https://github.com/FortAwesome/Font-Awesome/blob/b452a2c086a5e3f319df61b1ce1db7d8e1ad2b7c/js-packages/%40fortawesome/fontawesome-free/svgs/solid/magnifying-glass.svg (CC BY 4.0).
(note: Focusing `input` element, causing the …
> Replace Font Awesome with in-place SVG element for searchbox

- package-lock.json
- package.json
- webpack.config.js
Web font has been bundled by `url-loader`, which has delayed first page rendering and would make web font delivery faster with CDN than GitHub Pages.
Webpack Asset Modules can be used to replace.
- `.otf` is now separated from `https://bundler.io/application.css` to an individual file as `https://bundler.io/font/e68a5a6780c1d57a2eed.otf`.
- As no woff, woff2, ttf, eot, and svg files are not bundled by Webpack, the configuration for these kind of files is also removed.
- 1 `svg` file is linked from HAML, which has been simply copied on build by Middleman.
Updates part of #562
Webpack Asset Modules https://webpack.js.org/guides/asset-modules/ is considered as (relatively) modern.
> Replace url-loader with Webpack's Asset Modules

- assets/stylesheets/_bootstrap-overrides.scss
- assets/stylesheets/application.css.scss
Downloading the font blocks text rendering.
`font-display: swap` can be used.
`font-display: swap` is applied. Fallback fonts in `font-family` were updated to be in serif, not sans-serif, which is the default of Bootstrap.
`swap` looks like the best value for it while `failback` is available: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
> Use font-display: swap for performance

- data/contributors.yml
Contributors (`/contributors.html`) have not been updated for 7 months, which does not show appreciation for their contributions.
Update it via `rake build`.
Update `data/contributors.yml` with `bundle exec rake build` for the first time in 7 months after #542.
Quarterly, bi-monthly or monthly update might look good to me.
> Update on contributors in 2Q 2022

- source/v2.3/docs.html.haml
- #707
Also relevant to
- #691
Links can be added at minimum. All developer guides, generated from the main repo, already exist on Web site.
Adds a link from the sidebar in each guide (not command references) to [the top of contribution and developer guide](https://bundler.io/doc/readme.html).
1. A crawler and/or a user can find the entrance of from the Bundler Web site with this minimal change.
2. We can add dev guides on `https://bundler.io/docs.html`, but I skipped it **at this moment** since they are versioned.
> Add links to dev guides from user guides

- source/blog/feed.xml.builder
Use https in Blog feed `https://bundler.io/blog/feed.xml`.
Closes #711
> Use https in Blog feed

- assets/stylesheets/_blog.scss
- source/blog/index.html.haml
Blog top looks like the latest blog article, not home of blog.
Closes #714
Simplifying it is required.
- Remove the full body of the latest article, replaced by the link to it.
- Add year sections in reverse chronological order
- Drop unused/unnecessary CSS
| PC: before | PC: after |
|-|-|
|  ![bundler io_blog_](https://user-images.githubusercontent.com/10229505/179906097-51dc9afc-c7f7-4dbd-8a40-9396f44099b1.png) | ![bundler-site-redesign-b-kwkjux herokuapp com_blog](https://user-images.githubusercontent.com/10229505/179911330-b72b3668-6617-4527-ba05-c6aae74bc2d9.png) |
| Mobile: before | Mobile: after |
|-|-|
| ![bundler io_blog_(iPhone 12 Pro)](https://user-images.githubusercontent.com/10229505/179912616-edf5043f-4afa-4505-b25d-5d9981471832.png) | ![bundler-site-redesign-b-kwkjux …
> Redesign blog top

- source/blog/2022-01-23-bundler-v2-3.html.markdown
https://bundler.io/blog/2022/01/23/bundler-v2-3.html has a `h1` heading at the end of the article, which looks weird as other headings are all `h2` even if you want to emphasize "What's coming next?"
This would degrade search experience if we introduced a more semantic-based crawler in the future.
That section can be `h2` to align with other sections in the article.
Align that heading with other headings by changing from `h1` to `h2`.
Any reason may exist behind #596
> Copyedit Bundler v2.3 release blog article

- .rubocop.yml
- config.rb
Enable `Layout/ArgumentAlignment` cop in RuboCop.
Partially updates #672
> Enable Layout/ArgumentAlignment cop in RuboCop

- .github/workflows/build.yml
- .prettierrc
- assets/javascripts/application.js
- assets/javascripts/commands_layout.js
- assets/javascripts/search.js
- assets/javascripts/search_arrows.js
- package-lock.json
- package.json
JavaScript files are not so consistent.
Any linter for JavaScript files is not setup yet.
Introduce prettier as a linter for JavaScript files.
`singleQuote` looks preferred unlike [Prettier default](https://prettier.io/docs/en/options.html#quotes), so `singleQuote` is set `true` in this PR at this moment.
> Introduce prettier as JS linter

- assets/stylesheets/_sidebar.scss
`.truncate-text` was introduced in #231, but this has not been used for 5 years after #322 removed the last reference.
> Remove .truncate-text from CSS

- .github/workflows/build.yml
- .github/workflows/deploy.yml
This Web site is not a library and is expected to run with only a single Ruby version specified in `/.ruby-version`. The matrix has been introduced in #518 for a different purpose from the expectation. However, the original purpose was resolved in #558, but #558 missed this removal.
This will help us see GitHub status checks in pull requests since it becomes shorter.
Follows up #558
Updates #518
(The section `prettier` is not relevant)
> Pin ruby-version to 3.1.2 only without matrix

- .gitpod.yml
Removes one of status checks from Gitpod prebuild as it takes a longer time than others and Gitpod prebuild is not mandatory at this moment.
Updates #648
- #648
- https://www.gitpod.io/docs/references/gitpod-yml#prebuildsaddcheck
> Remove status checks from Gitpod prebuild

- config.rb
In #604, `commands.html.haml`s were deleted, but the rule for these files in Middleman was not. (cf. #536)
Follows up #604
> Remove page rule for deleted /v:ver/commands.html pages

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Use Ubuntu 22.04-based environment on Actions.
Closes #745
> Use Ubuntu 22.04-based environment on Actions

- config.rb
- source/layouts/layout.haml
Closes #747
This PR focuses on removal of `source/layouts/layout.haml`, which is the default filename. In addition, the most common layout in this project `source/layouts/base.haml` has been referred from customized layout files. In another place, we may change `base` to the default name.
> Remove source/layouts/layout.haml

- .github/workflows/deploy.yml
- lib/tasks/ci/deploy.rake
Purging cache from CDN (fastly) should be separated from deploy job.
The implementation was done in #241.
Relevant to #558
> Split rake tasks into deploy and purge

- source/layouts/base.haml
Disabling zooming is problematic for users with low vision who rely on screen magnification to properly see the contents of a web page.
We do not need to disable zooming at all.
Remove disabling zooming  (scaling).
No alternative these days. See also https://web.dev/meta-viewport/ .
> Unlock disabling zoom

- assets/stylesheets/_sidebar.scss
`.sidebar-brand`-related selectors were introduced in  https://github.com/rubygems/bundler-site/pull/218/commits/6ba978951705e186d2f1387932271ff5bef4806b as a part of #218.
`git grep sidebar-brand` and/or `git log -p | grep sidebar-brand`
Removes all selectors including `.sidebar-brand` from `assets/stylesheets/_sidebar.scss`.
We cannot go back to 2016, so just do it now.
> Remove never-used CSS selectors

- config.rb
- lib/tasks/versions.rake
- lib/versions.rb
I do not want to invoke a Rake command in the Middleman config.
This enables both Middleman and Rake tasks to have access to the variable directly.
> Refactor all available versions

- helpers/config_helper.rb
- source/partials/_commands_sidebar.haml
A visitor cannot see what version is active while 10 minor versions are listed.
Closes #760
Looks good to start with indicating the maintenance status per version rubygems/rubygems#5647.
Append the maintenance status per version next to each version in the version selector in the versioned man pages.
| before | after |
|-|-|
| ![bundler io_v2 3_man_bundle-viz 1 html](https://user-images.githubusercontent.com/10229505/180910676-53ba6f12-5cce-470c-a85b-f5d21f2aa0d3.png) | ![v2-closed](https://user-images.githubusercontent.com/10229505/181151816-28aaa9d4-64f0-41fe-b4ec-431171fb5fbe.png) |
| ![version-selector](https://user-images.githubusercontent.com/10229505/180910692-1d15cee5-1275-40c2-9a93-1c37aa8012a7.png) | ![v2-open](https://user-images.githubusercontent.com/10229505/181151821-17f132a4 …
> Append maintenance status per version

- lib/tasks/vendor_files.rake
- source/conduct.html.md
The contents updated in the upstream have not been applied to the Bundler Web site at all for more than two years.
Closes #770
We should apply all changes under `/bundler/doc/**` in https://github.com/rubygems/rubygems/compare/b0c1efd...1a12bab, that is:
<details><summary><code>git diff b0c1efd...1a12bab -- bundler/doc</code></summary>
````diff
diff --git a/bundler/doc/POLICIES.md b/bundler/doc/POLICIES.md
index b10d15559..dc6a3ec57 100644
--- a/bundler/doc/POLICIES.md
+++ b/bundler/doc/POLICIES.md
@@ -72,7 +72,7 @@ Contributors who have contributed regularly for more than six months (or impleme
-First off, Bundler's policies and enforcement of those policies are subsidiary to [Bundler's code of conduct](https://github.com/rubygems/bundler/blob/master/CODE_OF_CONDUCT.md) in any case where …
```
> Update the source of /doc and CoC as per the merger

- source/blog/2013-12-07-the-rumors-of-bundlers-death-have-been-greatly-exaggerated.html.markdown
- source/blog/2014-07-16-bundler-api-outages.html.markdown
- source/blog/2014-08-14-bundler-may-install-gems-from-a-different-source-than-expected-cve-2013-0334.html.markdown
- source/blog/2014-08-15-gem-not-found-error-on-1-7-0.html.markdown
- source/blog/2015-03-19-announcing-ruby-together.html.markdown
- source/blog/2015-06-24-version-1-10-released.html.markdown
- source/blog/2016-04-28-the-new-index-format-fastly-and-bundler-1-12.html.md
- source/blog/2016-09-08-bundler-1-13.html.md
As `arko.net` supports for HTTPS, these URLs can be updated.
> Use https for arko.net

- source/blog/2013-10-12-goodbye-bundler-14-hello-bundler-15.html.markdown
Heroku's subdomain has been under `herokuapp.com` instead of `heroku.com` for so many years.
> Heroku domain is now on herokuapp.com

- source/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
`https://support.apple.com/kb/PH25523` is now dead.
> Fix dead link for Set the date and time on your Mac

- .github/workflows/build.yml
- .github/workflows/test.yml
- .haml-lint.yml
- Gemfile
- Gemfile.lock
- Introduce HAML-Lint for HAML files
- Reorganize Action workflow files
Closes #774
Note: this does not include fix in single/double quotes due to missing RuboCop configurations (see #775)
> Introduce HAML-Lint for HAML files

- .haml-lint.yml
- source/contributors.html.haml
- source/layouts/_favicon.haml
- source/layouts/blog_layout.haml
Prior to #775, remove `exclude` from the `RuboCop` rule in HAML-Lint.
> Enable RuboCop entirely in HAML-Lint

- source/localizable/index.html.haml
Contents in paragraphs in the top page tends to be slightly short but Bootstrap 5 has provided the capabilities for larger screens than FHD(WQHD, 4K etc.)
- Current width of div: 1296dp
- Updated width of div: 1104dp
Closes #697
Follows up #681
> Add extra margins on sides on top

- assets/stylesheets/application.css.scss
- source/404.html.haml
- source/localizable/index.html.haml
Remove .btn-margin-top CSS introduced in https://github.com/rubygems/bundler-site/pull/218/commits/ce8a254ac774b834310f9afd625b3b977fbc7e2b by replacing it with Bootstrap 5 framework. 
Fixes up #218
> Remove .btn-margin-top CSS

- lib/tasks/ci/deploy.rake
- lib/tasks/ci/ssh_repo.rake
- lib/tasks/release.rake
- lib/tasks/vendor_files.rake
Closes #591
Changes the publishing source for GitHub Pages for `https://bundler.io`.
- before: https://github.com/rubygems/bundler.github.io/tree/master
- after: https://github.com/rubygems/bundler-site/tree/gh-pages
- `ci:update_ssh_site` Rake task does now use HTTPS over SSH per [GitHub recommendation](https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories) and thanks to pre-defined token in GitHub Actions. Unify it with `update_site` Rake task in another PR.
- `configure_ssh_deploy_key` remains. Remove it in another PR.
- Permissions in GitHub Actions are not changed. Improve it in another PR.
- New Custom GitHub Actions Workflows (beta) for GitHub Pages are not included. See https://github.com/middleman/middleman/issues/2561
- or …
> Use the same repository but the different branch for GitHub Pages for production

- lib/tasks/ci/ssh_repo.rake
Fixes up #789
While in #789, we changed the protocol from SSH to HTTPS along with changes on the repository (#591), it did not work. This PR reverts the protocol to SSH.
> Use SSH protocol for git push on deploy job

- .github/workflows/deploy.yml
- lib/tasks/ci/ssh_repo.rake
`actions/checkout` sets up the configuration for authentication to `rubygems/bundler-site` with Read/Write permission. As a workaround until #790 completes, we can use that configuration in `vendor/ssh_bundler.github.io`, copying `git config` (`.git/config`).
Fixes more up #789
Reverts #791
> Use git config prepared by actions/checkout

- .github/workflows/deploy.yml
- lib/tasks/ci/deploy.rake
- lib/tasks/ci/ssh_repo.rake
- lib/tasks/vendor_files.rake
Fixes up #789 and #793
Now `ci:deploy` task is independent from `ci:update_ssh_site` task 🎉 
> Use gh-pages branch on deploy

- .github/workflows/deploy.yml
- config.rb
With [the release of Custom GitHub Actions Workflows (beta) for GitHub Pages](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/) on July 27, 2022, we can benefit from it to make the publishing source from `gh-pages` branch to `main` after #591 (= #794 + #789).
Closes #790
> Migrate the deploy Action from homemade to the official

- .github/workflows/deploy.yml
Follows up #795
As #795 did not update the contents in `https://bundler.io`, I think no downtime on `bundler.io` happened during #795 and this PR.
- #795
> Enable the custom domain again even in custom workflow

- lib/tasks/ci/deploy.rake
We do not use SSH key to pull/push the repository due to #591.
> Remove operations for SSH key from ci:deploy

- source/layouts/base.haml
We should align with meta tag:
```haml
%meta(http-equiv="Content-Language" content="#{I18n.locale.to_s}")
```
> Use i18n locale in html lang

- README.md
For visibility for contributors. Link target is [the Deployment page](https://github.com/rubygems/bundler-site/deployments/activity_log?environment=github-pages), not [the deploy workflow on Actions](https://github.com/rubygems/bundler-site/actions/workflows/deploy.yml?query=branch%3Amaster).
> Add the badge of Pages to README

- config.rb
`https://bundler.io/v1.12/bundler_setup.html` has not been redirected to `https://bundler.io/v1.15/guides/bundler_setup.html` correctly.
Fixes up #669
> Fix redirection rules for older guides before 1.15

- assets/javascripts/application.js
- assets/javascripts/two_column_layout.js
After #806, we can clean up more code around AnchorJS. Now only `assets/javascripts/two_column_layout.js` is using AnchorJS, and so we can move the option there.
Partially removes render-blocking JavaScript. cf. https://www.bryanbraun.com/anchorjs/#dont-run-it-too-late
> Clean up application.js around AnchorJS

- source/partials/_team_member.haml
- Not to use `<b>`.
- Not to use `<h5>`.
`h4` is not changed since CSS is applied to them.
> Remove h5 elements when they are not necessary

- assets/javascripts/two_column_layout.js
This option works no more in many browsers as expected in #218.
- https://caniuse.com/touch
- https://github.com/bryanbraun/anchorjs/issues/168
Closes #816
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://caniuse.com/touch)
> Remove touch option from AnchorJS

- assets/javascripts/two_column_layout.js
1. AnchorJS has [`h2, h3, h4, h5, h6` as default](https://github.com/bryanbraun/anchorjs/blob/e953150d8e50ebc84f490eb11207845803239234/anchor.js#L89) and follow it. In general, a page has only single `h1` element, so we do not need to use anchor.
2. The site has 51 `h1` tags in 50 files generated by `rake build`.
> Remove h1 from AnchorJS target

- config.ru
Make deployment to Heroku review apps robust to support non-default `build_dir` configuration in Middleman.
Follows up #815 
> Support non-default build_dir in a Rack server

- lib/tasks/man_generator/strip_pages.rake
Use `h1` tag for the command name in command reference, instead of `h2`, which is generated by `ronn`.
> Use h1 instead of h2 for command name in command reference

- .gitpod.Dockerfile
- .gitpod.yml
Updates #648
As `gitpod-io/workspace-full` image, the default image from gitpod-io/workspace-images is now based on both Ruby 3.1.2 and Node.js 16.x, we do not need to built it by ourselves.
- https://github.com/gitpod-io/workspace-images/pull/889
> Update gitpod workspace with the default

- locales/en.yml
- locales/es.yml
- locales/pl.yml
- source/guides/getting_started.html.haml
- source/localizable/index.html.haml
Removes gem install bundler from getting started (in [the top page](https://bundler.io/) and [the dedicated page](https://bundler.io/guides/getting_started.html)).
Last resort for older Ruby's without Bundler bundled is `https://bundler.io/v1.15/guides/using_bundler_in_applications.html` as of writing.
Closes #763 
> Remove gem install bundler from getting started

- lib/templates/whats_new.html.haml.erb
- source/shared/_whats_new.haml
- source/v1.12/whats_new.html.haml
- source/v1.13/whats_new.html.haml
- source/v1.14/whats_new.html.haml
- source/v1.15/whats_new.html.haml
- source/v1.16/whats_new.html.haml
- source/v1.17/whats_new.html.haml
- source/v2.0/whats_new.html.haml
- source/v2.1/whats_new.html.haml
- source/v2.2/whats_new.html.haml
- source/v2.3/whats_new.html.haml
Moves the navigation to what's new pages in other versions to bottom and adds the `h1` heading titled as `What's New in vX.Y`.
Closes #827
| before | after |
|-|-|
| ![bundler io_v1 12_whats_new html](https://user-images.githubusercontent.com/10229505/182031308-6f372dfd-ce27-43f5-b301-8f72fe81b50f.png) | ![4567-rubygems-bundlersite-xaimk8cdg5n ws-us58 gitpod io_v1 12_whats_new html](https://user-images.githubusercontent.com/10229505/182032483-a82baeb9-7cd1-4855-a23a-c86d290dda73.png) |
> Clean up whats new pages

- .github/workflows/build.yml
Updates #493
We should check if all builds pass. `rake build` triggers `contributors:update`, `repo_pages`, `man` tasks before `middleman build`.
> Use full build to test man, repo page, contributors build

- source/v2.1/bundle_plugin.html.haml
- source/v2.2/bundle_plugin.html.haml
- source/v2.3/bundle_plugin.html.haml
Headings in `bundle plugin` (https://bundler.io/v2.3/bundle_plugin.html for v2.3) are `h2` tag instead of `h1`, which is the standard formatting.
Also meta description is missing.
Closes #832
Replace h2 with h1 in the command title.
Add meta description for SEO.
Use h1 in bundle plugin (only v2.1 through v2.3).
We could migrate this doc to rubygems/rubygems, but I do not think it is so easy to do so against v2.1 and v2.2.
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/tnir)
> Use h1 in bundle plugin

- source/guides/rails.html.haml
- source/v1.15/guides/rails.html.haml
Anchors unused for 6 years in Rails guides (https://bundler.io/guides/rails.html etc.) violates HAML-Lint, which blocks #860.
Closes #861
Updates #257
Blocks #860
It is confirmed that no internal reference has existed for 6 years i.e., #257.
Removes these anchors from Rails guides https://bundler.io/guides/rails.html and https://bundler.io/v1.15/guides/rails.html.
No other options to us.
> Remove anchors unused for 6 years from Rails guides

- source/guides/bundler_plugins.html.haml
- source/guides/bundler_workflow.html.haml
Formatting in id attributes varies over HAML files.
Blocks #860
Updates #250 and #530
HAML-Lint has lisp-case as the default style, which can be used in this project.
Uses kebab-case (or lisp-case) in HAML files.
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/tnir)
> Use kebab-case (or lisp-case) in HAML files

- source/guides/bundler_2_upgrade.html.md
- source/guides/bundler_workflow.html.haml
- source/guides/getting_started.html.haml
- source/localizable/index.html.haml
- source/v1.15/guides/git.html.haml
rack 2.2.3 and earlier has CVE-2022-30123: https://groups.google.com/g/ruby-security-ann/c/LWB10kWzag8
Avoid to suggest to use rack version without vulnerabilities as an example.
Update rack to 2.2.4 in all the examples.
> Avoid to use vulnerable gem as examples

- .haml-lint.yml
`RepeatedId` linter in HAML-Lint was not enabled in #776.
#863 addressed lints against `RepeatedId`.
Enables `RepeatedId` for all files in HAML-Lint.
n/a
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/tnir)
> Enable RepeatedId for all files in HAML-Lint

- .haml-lint.yml
- source/layouts/base.haml
Some linters were disabled when HAML-Lint was introduced in #776.
`HtmlAttributes` HAML linter can be enabled for all files.
Removes exclusion of files with lints and enables the linter.
n/a
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/tnir)
> Enable HtmlAttributes for all files in HAML-Lint

- Gemfile.lock
https://github.com/rubygems/rubygems/releases/tag/bundler-v2.3.21
> Update Bundler from 2.3.14 to 2.3.21

- assets/stylesheets/application.css.scss
- source/localizable/index.html.haml
https://github.com/rubygems/bundler-site/pull/218/commits/8bdc09ee50bda18107e1532bca69c126d9486ccd introduced hard-coded `.btn` and `.btn-responsive` in #218, but they have been conflicted with general specifications and the framework (i.e., Bootstrap 5).
- Follows up #785
- Follows up #644
We can remove them for now as the major framework migration was done in #681.
Removes CSS selectors `.btn` and `.btn-responsive` with spacing tweaks around these occurrences mainly to make these buttons fully responsive on the top page besides removal of the technical debt. Some are what #218 intended to achieve, but failed.
Note that this change affects only the top page.
| Screen width / px | Before | After |
|-|-|-|
| 320 | ![bundler io_w320](https://user-images.githubusercontent.com/10229505/1870338 …
> Remove some CSS selectors with tweaks around them

- source/older_versions.html.haml
`/older_versions` is now redirected to `/whats_new` since #687.
- Follows up #687
- Closes #897
> Remove source/older_versions.html.haml

- config.rb
https://middlemanapp.com/basics/redirects/ says:
> To generate a redirect in Middleman, add the following to `config.rb`:
> 
> ```
> redirect "my/old/path.html", to: "/my/new/path.html"
> ```
> 
> The old path should not have a leading slash and should refer to a file such as `path/index.html`, not just a path.
Fixes up #718
> Middleman redirects require index.html in the old paths

- Gemfile.lock
Bumps [mustache](https://github.com/sporkmonger/addressable) from 1.0.5 (2017-03) to 1.1.1 (2019-12).
- [Release notes](https://github.com/mustache/mustache/blob/v1.1.1/HISTORY.md)
- [Changelog](https://github.com/mustache/mustache/blob/v1.1.1/HISTORY.md)
- [Commits](https://github.com/mustache/mustache/compare/v1.0.5...v1.1.1)
- [Versions diffs](https://my.diffend.io/gems/mustache/1.0.5/1.1.1)
> Bump mustache from 1.0.5 to 1.1.1

- Gemfile.lock
https://my.diffend.io/gems/rb-fsevent/0.11.1/0.11.2
> Bump rb-fsevent from 0.11.1 to 0.11.2

- Gemfile
- Gemfile.lock
Update middleman from 4.4.2 to 4.4.2 (e1ef056) just to update contracts to 0.17.0 and listen to 3.7.1 first.
Blocks #901
- https://github.com/middleman/middleman/pull/2566
- Full diff: https://github.com/tnir/middleman/compare/v4.4.2...4.x-backport-936d19c
> Update middleman from 4.4.2 to 4.4.2 (e1ef056)

- Gemfile
- Gemfile.lock
Unlocks activesupport version.
Follows up #905 and #901
- #905
- #901
- https://github.com/middleman/middleman/pull/2552
> Update activesupport from 6.1.6.1 to 7.0.3.1

- assets/stylesheets/_sidebar.scss
- source/layouts/two_column_layout.haml
CSS animation in sidebar introduced from [Simple Sidebar](https://startbootstrap.com/template/simple-sidebar) in #218 is not semantic.
https://user-images.githubusercontent.com/10229505/188497467-67769b4e-f131-4cd7-b022-13e8c0f0e22a.mov
Removes that CSS tweak and the the relevant identifier.
https://user-images.githubusercontent.com/10229505/188499371-0aa07bb7-ec13-4cb7-9a37-8ee4c39578a6.mov
n/a
> Remove messy CSS tweaks introduced from Simple Sidebar

- source/v1.12/bundle_console.html.md
- source/v1.12/bundle_help.html.md
- source/v1.13/bundle_console.html.haml
- source/v1.13/bundle_help.html.haml
- source/v1.14/bundle_console.html.haml
- source/v1.14/bundle_help.html.haml
- source/v1.15/bundle_console.html.haml
- source/v1.15/bundle_help.html.haml
- source/v1.16/bundle_console.html.haml
- source/v1.16/bundle_help.html.haml
- source/v1.17/bundle_console.html.haml
- source/v1.17/bundle_help.html.haml
- source/v2.0/bundle_console.html.haml
- source/v2.0/bundle_help.html.haml
- source/v2.1/bundle_console.html.haml
- source/v2.1/bundle_help.html.haml
- source/v2.2/bundle_console.html.haml
- source/v2.2/bundle_help.html.haml
This standardized consistency in marking up would offer readability as well as a better search experience.
- Closes #836
- Closes #919
> Prefer h1 over h2 for the most top-level headings

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
[`ruby/setup-ruby`](https://github.com/ruby/setup-ruby) can automatically detect the version required in Actions.
Closes #857
cf. https://github.com/ruby/setup-ruby/blob/3068fa83f9cbd7ae106cac45483635a2f3a195c9/README.md#supported-version-syntax
> Do not repeat .ruby-version in Actions

- config.rb
- lib/tasks/vendor_files.rake
- source/blog/2016-04-28-the-new-index-format-fastly-and-bundler-1-12.html.md
- source/blog/2016-09-08-bundler-1-13.html.md
- source/blog/2018-01-08-monthly-update-for-december-and-yearly-update-for-2017.html.markdown
- source/blog/2019-01-03-announcing-bundler-2.html.markdown
- source/guides/bundler_plugins.html.haml
- source/guides/git_bisect.html.md
- source/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
- source/v1.15/guides/git_bisect.html.md
With this PR, there will be the only one occurrence of `bundler/bundler`, which can be left alone as it is just a history.
```
$ git grep bundler/bundler
source/blog/2020-04-27-march-monthly-update.html.markdown:[...] On GitHub, `bundler/bundler` is archived, [...]
```
- `https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md` (removed in https://github.com/rubygems/rubygems/pull/4980)
- (in the context for asking an issue) `https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md`
- (in the troubleshooting context) `https://bundler.io/doc/troubleshooting.html`
---
- Last part of #553
Closes #553
> Replace links to bundler/bundler with appropriate things

- Gemfile
- Gemfile.lock
The problem was that tnir's branch has been merged to the middleman/middleman repo, and it's perhaps more legible to refer to that repository.
- The desired Pull Request has been merged.
- I added a comment about a HAML 6-supporting change, as well. Perhaps we can begin using HAML 6, soon. https://haml.info/docs/yardoc/file.CHANGELOG.html looks meaty, that release. 1.7x quicker. Oh, perhaps https://github.com/rubygems/bundler-site/pull/918 is fixed, by this change.
My diagnosis was that it would be easier to understand if we referred to the middleman/middleman repo instead of tnir's, now that the PR is merged.
My fix is to use the source repo, not the forked one, in our Gemfile.
N/A.
> Gemfile: use middleman/middleman from git

- assets/stylesheets/_bootstrap-class-overrides.scss
- assets/stylesheets/_bootstrap-variable-overrides.scss
- assets/stylesheets/application.css.scss
Closes #684
I changed the `.btn-primary` colors to `#0D7FA5` and `#0A6A8A`, this colors provide a contrast ration of [4.56:1](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=0D7FA5) and [6.1:1](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=0A6A8A), respectively.
I also renamed the file `_bootstrap-overrides.scss` to `_bootstrap-variable-overrides.scss`, and created the file `_bootstrap-class-overrides.scss`, this modifications is just to improve the code organization.
**Before**
**After**
**Original colors with black text (just for comparison)**
_*The first button has the hover effect active._
I chose this fix because it was already discussed before.
> Make buttons easier to read

- config.rb
#618
My fix redirects all requests for `/man/*.html` to `/<latest_bundler_version>/man/*.html` using `redirect`.
I chose this fix because it follows the project standards and is very simple.
> Redirect to the latest man page when version isn't specified

- config.rb
- helpers/docs_helper.rb
- helpers/guides_helper.rb
The problem was that when running `bin/rake versions:create`, a few warnings are printed:
```
/Users/deivid/Code/rubygems/bundler-site/helpers/docs_helper.rb:2: warning: already initialized constant DocsHelper::ADDITIONAL_PAGES
/Users/deivid/Code/rubygems/bundler-site/helpers/docs_helper.rb:2: warning: previous definition of ADDITIONAL_PAGES was here
/Users/deivid/Code/rubygems/bundler-site/helpers/guides_helper.rb:2: warning: already initialized constant GuidesHelper::LOCALIZABLE_REGEX
/Users/deivid/Code/rubygems/bundler-site/helpers/guides_helper.rb:2: warning: previous definition of LOCALIZABLE_REGEX was here
/Users/deivid/Code/rubygems/bundler-site/helpers/guides_helper.rb:3: warning: already initialized constant GuidesHelper::ADDITIONAL_GUIDES …
```
> Fix double load warnings

- .github/workflows/build.yml
- lib/tasks/contributors.rake
The problem was that sometimes CI can fail due to API calls to the GitHub API getting rate-limited.
My diagnosis was, thanks to the helpful error message, that we should be doing authenticated calls.
My fix is to use the `GITHUB_TOKEN` available in CI to authenticate the API calls.
> Fix octokit getting rate-limited in CI

- .haml-lint.yml
- lib/templates/whats_new.html.haml.erb
- source/v1.13/whats_new.html.haml
- source/v1.14/whats_new.html.haml
- source/v1.15/whats_new.html.haml
- source/v1.16/whats_new.html.haml
- source/v1.17/whats_new.html.haml
- source/v2.0/whats_new.html.haml
- source/v2.1/whats_new.html.haml
- source/v2.2/whats_new.html.haml
- source/v2.3/whats_new.html.haml
The problem was that when adding a new minor version to the documentation site, we need to remember to add exclusions to haml-lint configuration or else haml-lint will fail.
My diagnosis was that we can fix the haml-lint offenses, to get cleaner templates and also not have to remember to add new exclusions when we add new versions.
My fix is to fix the offenses and the template.
I chose this fix because just adding new exclusions was inferior in terms of maintainability.
> Fix some haml-lint offenses

- Gemfile.lock
`bundler-site` is still using Bundler 2.3.x.
This site should use Bundler 2.4 (latest).
Use Bundler 2.4.1 on build.
n/a
- https://github.com/rubygems/rubygems/pull/6191
> Use Bundler 2.4.1

- source/compatibility.html.haml
https://bundler.io/compatibility.html is now mis-leading since Bundler 2.4.0 was just released: https://rubygems.org/gems/bundler/versions/2.4.0
Bundler 2.4 requires both Ruby 2.6 or higher and RubyGems 3.0.1 or higher (https://github.com/rubygems/rubygems/pull/6107).
Adds entries for Bundler 2.4 or higher and fixes the existing entries for Bundler 2 with Bundler 2.0-2.3.
No other option is not considerable.
> Update compatible versions of Ruby/RubyGems with Bundler 2.4

- .github/workflows/deploy.yml
The problem was the deployment task can fail due to GitHub API rate limiting due to the same issue as #980.
My diagnosis was the we should also use authenticated API calls when deploying.
My fix is to apply the same solution as #980.
> Fix rate limit when building site for deployment

- helpers/config_helper.rb
- source/v2.4/docs.html.haml
- source/v2.4/whats_new.html.haml
The problem was that I want to hold just a bit on publish the blog post, but that shouldn't block publishing documentation pages for Bundler 2.4.
My diagnosis was that we should extract documentation from #978.
My fix extract documentation to this PR. Include a bare "What's new page" with just a link to the changelog for now.
I chose this fix because it unblocks @tnir :)
> Add Bundler 2.4 to documentation

- config.rb
Reverts #965 as it simply caused the bug.
Reopens #990
- See https://github.com/rubygems/bundler-site/pull/965#issuecomment-1357282797
> Revert "Redirect to the latest man page when version isn't specified"

- config.rb
- lib/tasks/man_generator/man.rake
The problem was some pages render as plain text.
Link for "Edit this document on GitHub" is broken in top-level `/man/` pages (#930).
My diagnosis was that we should get rid of 
```ruby
page /\/man\/(.*)/, layout: false
```
from our config, since that's what's rendering content without a layout.
My fix is to remove that line and fix the issues that come up after doing that.
I chose this fix because it fixes #992 without regressing #930.
> Stop making plain text pages available at the top level

- Gemfile
- Gemfile.lock
The problem was that the Ronn gem and its dependencies have been abandoned for 10 years. It has worked pretty well so far but we're seeing some unstability now. In particular, we've seen some C-level crashes inside the hpricot dependency.
My diagnosis was that we should migrate to newer alternatives.
My fix is to migrate to the currently maintained fork, [ronn-ng](https://github.com/apjanke/ronn-ng). I also needed to pick up [one fix](https://github.com/n-ronn/nronn/commit/09be8af91dcb01693848a9884d66a011235ce6ac) by @tnir.
I will propose this fix to ronn-ng and ask whether they would allow us to get commit and release access there.
I chose this fix because creating [yet another fork](https://github.com/n-ronn/nronn) as in #841 seems worse for the community so we could try the existing …
> Migrate from `ronn` to `ronn-ng`

- source/blog/2018-06-07-may-bundler-update.html.markdown
- source/blog/2018-09-10-august-bundler-update.html.markdown
- source/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
Some links in the site are still linking to `/:version/guides/:slug.md`, which should be now correctly redirected to `/guides/:slug.md`.
#651 avoided to update links in the contents.
Follows up #651.
Replace `/:version/guides/` wth `/guides/` in files under`/source`.
Makes it easier for maintainers to update links in the future.
> Update internal links to versioned guides with the latest ones

- Gemfile.lock
`activesupport` used in this repo is not up-to-date.
https://github.com/rails/rails/blob/v7.0.4/activesupport/CHANGELOG.md
Updates activesupport gem from 7.0.3.1 to 7.0.4.
To make the following changes minimal.
> Update activesupport from 7.0.3.1 to 7.0.4

- source/localizable/index.html.haml
All links to `slack.bundler.io` have been `http`-protocol based for a long time.
In late 2010s, we should use `https`. It is (almost) 2023.
Forces to use https against `slack.bundler.io`.
https://www.ssllabs.com/ssltest/analyze.html?d=slack.bundler.io&latest supports this change as well.
In this PR, the PR author does not care about why so many links on the top page 😭 
> Use https instead of http for links to slack.bundler.io

- Gemfile
- Gemfile.lock
Current version of middleman-search does not support Ruby 3.2 as its syntax is too legacy.
Ruby 3.2-ready code is available at https://github.com/manastech/middleman-search/pull/39 or https://github.com/tnir/middleman-search/tree/edge.
Makes the code ready to use Ruby 3.2.
Once https://github.com/manastech/middleman-search/pull/39 is merged, we can use the upstream.
> Update middleman-search to edge to use Ruby 3.2

- Gemfile
- Gemfile.lock
- Closes #1003
~~Use nronn to unify use of rdiscount with kramdown, and to unify use of hpricot with nokogiri.~~
1. rdiscount and kramdown both provide similar functionality: avoid to use rdicount
2. hpricot and nokogiri both provide similar functionality: avoid to use hpricot
3. Tested with Ruby 3.1 in CI (ronn has never continuously tested 😭).
> Replace missing forked ronn-ng with public nronn

- source/guides/bundler_workflow.html.md
A link in https://bundler.io/guides/bundler_workflow.html is dead.
Following up #651 is missing 😢 .
Use the absolute link instead.
Leaving deadlinks should be harmful.
> Use the absolute link in guides/bundler_workflow

- .haml-lint.yml
- source/layouts/base.haml
- Follows up #776
To minimize .haml-lint.yml and to clean up HAML code.
> HAML-Lint: cleanup UnnecessaryStringOutput

- Gemfile.lock
We still use kramdown-parser-gfm 1.0.1, which was released in 2019 (4 years ago).
🎉 https://github.com/kramdown/parser-gfm/blob/master/CHANGELOG.md#110--2019-05-29
Simply we can use the latest published version of [kramdown-parser-gfm](https://rubygems.org/gems/kramdown-parser-gfm).
Forces to use kramdown-parser-gfm 1.1.0 instead of 1.0.1
But 1.1.0 was released in 3.5+ years ago.
> Update kramdown-parser-gfm from 1.0.1 to 1.1.0

- Gemfile.lock
See https://github.com/rack/rack/pull/1998 for Ruby 3.2.0
Nothing. But we will encounter some problem described in https://github.com/rack/rack/pull/1998 for Ruby 3.2.0 since we are already in 3.2.0 #984.
We cannot use rack 3.0 since middleman blocks it.
Updates rack from 2.2.4 to 2.2.5.
Maybe we can allow middleman to use rack 3.0 if we have time to contribute middleman.
> Update rack from 2.2.4 to 2.2.5

- Gemfile.lock
`oj`, which was dependent from `middleman-core` is not up-to-date.
https://github.com/ohler55/oj/blob/v3.13.23/CHANGELOG.md
Just updates oj from 3.13.21 to 3.13.22.
I hope to have indirect updates (note that https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow shows `indirect` is not supported for `rubygems`)
> Update oj from 3.13.21 to 3.13.22

- Gemfile.lock
Release note of rack 1.6.2 missed the largest change: https://github.com/ruby/racc/commit/9b0a22c999c3c55ec2aca585468d456d1eca2378
- https://github.com/ruby/racc/releases/tag/v1.6.2
- https://github.com/ruby/racc/compare/v1.6.1...v1.6.2
> Update racc from 1.6.1 to 1.6.2

- Gemfile.lock
https://github.com/weppos/publicsuffix-ruby/compare/v5.0.0...v5.0.1
Nothing special.
> Update public_suffix from 5.0.0 to 5.0.1

- Gemfile.lock
minitest is just depended by activesupport 😢 
> Update minitest from 5.16.3 to 5.17.0

- package-lock.json
"webpack#browserslist" depends on `caniuse-lite`.
> Update caniuse-lite from 1.0.30001285 to 1.0.30001441

- package-lock.json
https://github.com/terser/terser/blob/v5.16.1/CHANGELOG.md
This allows us to use ES 2022 🎉 
> Update terser from 5.14.2 to 5.16.1

- Gemfile
- Gemfile.lock
The problem was that after https://github.com/apjanke/ronn-ng/pull/83 got merged, and deleted the branch in my fork and that blocked further deployments of our documentation site as per https://github.com/rubygems/bundler-site/issues/1003.
My diagnosis was that I should've been more careful. Switch back to ronn-ng's main branch here first, and only then delete my branch.
My fix is to switch back to main branch of ronn-ng
I chose this fix because my understanding is that merging https://github.com/rubygems/bundler-site/pull/841 was just a temporary fix to unblock deployments.
> Go back to ronn-ng

- config.rb
This comment claims that `https://bundler.io/v1.15/bundler_setup.html` redirects to `https://bundler.io/guides/bundler_setup.html`, but that's not true. 
Fix the comment to describe reality.
> Fix redirect comment

- Gemfile.lock
https://github.com/rubygems/rubygems/releases/tag/bundler-v2.4.2
> Update bundler from 2.4.1 to 2.4.2

- Gemfile.lock
https://my.diffend.io/gems/terser/1.1.12/1.1.13
While we are already on 5.16.1 😬 #1020
> Update terser from 1.1.12 to 1.1.13

- .haml-lint.yml
As #1045, #1006, #1046, and #1027 removed all files with exceptions, now we can remove these exceptions for `IdNames` linter from `.haml-lint.yml`.
> Remove exceptions for IdNames linter from .haml-lint.yml

- source/localizable/index.html.haml
- It seems that  page link of "New in v2.4"  button on https://bundler.io/  is incorrect because the link missing version path
- I can see the page with https://bundler.io/v2.4/whats_new.html 
- Missing version in the  `whats_new.html ` page link
- Fix the link to contain version like `https://bundler.io/v2.4/whats_new.html `
- Because I found these links that contain version
- https://bundler.io/v2.2/whats_new.html
- https://bundler.io/v2.3/whats_new.html
- https://bundler.io/v2.4/whats_new.html
> Add current_version to whats_new link

- source/guides/bundler_setup.html.md
- source/guides/bundler_workflow.html.md
- source/guides/getting_started.html.md
- source/guides/groups.html.md
- source/guides/rationale.html.md
- source/guides/sinatra.html.md
- source/localizable/guides/bundler_setup.es.html.md
`require 'rubygems'` lines still exist in the docs.
We do not need `require 'rubygems'` any more.
Removes `require 'rubygems'`.
The document does not have to support Ruby 1.8 and earlier in 2023.
> You do not have to reuqire rubygems on Ruby 1.9+

- source/blog/2023-01-31-bundler-v2-4.html.markdown
- source/blog/2023-01-31-rust-gem-skeleton.html.markdown
- source/v2.4/whats_new.html.md
The problem was the we should announce the upcoming Bundler 2.4 release.
My fix is to draft a release blog post and a "What's new" page.
> Add Bundler 2.4 blog post and release notes

- source/localizable/index.html.haml
- this link is configured to never expired
- it seems to be limited to 400 uses, but better than nothing for now :pray:
> Update Slack invite link.

- Gemfile.lock
Nothing
The developer of this site would use the latest version of Bundler as of writing.
https://rubygems.org/gems/bundler/versions/2.4.12 is the latest version of Bundler.
Update Bundler to 2.4.2 to 2.4.12 (latest).
Dogfooding might be better than nothing.
> chore(deps): update bundler from 2.4.2 to 2.4.12

- package-lock.json
postcss npm package is now stale.
postcss 8.4.23 is already available, as of writing, which includes some bugfix shown in https://github.com/postcss/postcss/releases/tag/8.4.22.
Update postcss from 8.4.20 to 8.4.23 and nanoid from 3.3.4 to 3.3.6.
Nothing considered.
> chore(deps): update postcss from 8.4.20 to 8.4.23

- source/guides/getting_started.html.md
- source/localizable/index.html.haml
The problem was that it was not clear that you don't really need to install Bundler if you have Ruby installed.
My fix is to make it explicit that Ruby comes with Bundler by default.
> Clarify that Bundler comes preinstalled by default

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- Follows up PR #1156
n/a
They will not want to use Node.js 16, which will be EOL'd very soon.
CI can use Node.js 18, which is the current active LTS.
Node.js 18 is used instead of 16 even on CI.
Node.js 16 will be EOL'd in 2-3 months.
> chore(deps): update Node.js to 16.x to 18.x on CI

- source/guides/git.html.md
I just noticed a small grammar error in the documentation.
Subject-verb agreement was incorrect: "... every time the local git repository change, ..."
Change the phrase to read "... every time the local git repository changes, the changes will be automatically picked up by Bundler."
It's a straightforward fix that corrects the grammar and makes it sound correct to native English readers without changing the meaning.
> Fix grammar (subject-verb agreement) in git.html.md

- data/known_plugins.yml
- lib/tasks/regenerate_known_plugins_yml.rake
- source/guides/bundler_plugins.html.md
- source/guides/plugins.html.haml
closes #505
and update the rake task. use RubyGems itself to fetch data from rubygems.org, and actually filter gems by ones that have a proper Bundler plugins.rb.
> Update known_plugins.yml and its Rake task

- data/known_plugins.yml
- lib/tasks/regenerate_known_plugins_yml.rake
The problem was that two plugins were seen which ought to have been skipped.
Their functionality's now built-in.
My diagnosis was that the skip list was not updated.
My fix was to extend the skip list with two more gems.
Also, I ran the Rake task, to get the result seen in data/.
I chose this fix because I got a good hint.
Fixes #1231
> Skip two Bundler plugins known to be outdated

- data/known_plugins.yml
- lib/tasks/regenerate_known_plugins_yml.rake
Its source does not exist, and its summary explicitly says the problem has been fixed in Bundler 2.1.0
The gem should not be listed.
Skip it.
Precedent of skipping other outdated plugins.
> Skip bundler-shellsplit-plugin

- config.rb
- lib/tasks/vendor_files.rake
The problem was that a link to the CHANGELOG was 404ing. So, (in a now-closed PR) I made the link absolute, instead of relative, to work around the problem.
But, that'd take us to another website to look at Bundler's CHANGELOG. It'd be nice if Bundler's website knew about the CHANGELOG - had it locally.
My diagnosis was we didn't have all files that would be necessary to create a local CHANGELOG, we'd have to point outside this repo, to some on-GitHub data, not very nice. Not rendered in this nice way.
Include CHANGELOG as a file in the generated site.
This fixes #1233.
This fixes #846 
I chose this fix because we mentioned it in #1233.
> Add CHANGELOG as vendored file

- Gemfile
- Gemfile.lock
Using the fork released to rubygems.org is what @tnir did initially at https://github.com/rubygems/bundler-site/pull/841, but I reverted that at https://github.com/rubygems/bundler-site/pull/1021 because:
* I wasn't sure if it was intentionally permanent or just to unlock deployments.
* I wanted to be ronn-ng one last chance.
* ### What was your diagnosis of the problem?
My diagnosis was that ronn-ng has not really got any traction and I decided to move on to nronn in Bundler at https://github.com/rubygems/rubygems/pull/7227.
My fix is to also migrate to nronn here.
I chose this fix because it sounds like the best path going forward.
> Back to nronn

- helpers/config_helper.rb
- source/v2.5/docs.html.haml
- source/v2.5/whats_new.html.md
Bundler 2.5.0 was successfully released on 2023-12-15, and it is still hard for end-users to find Bundler 2.1 to be fully deprecated.
- https://rubygems.org/gems/bundler/versions/2.5.0
- The latest should be Bundler 2.5.
- This publishes Bundler 2.5 as the latest version.
- This also marks Bundler 2.1 as legacy.
No other possible options.
- Previous update (bundler 2.4): #991
> rel: add Bundler 2.5 as the latest version to docs

- source/guides/rails.html.md
A missing newline causes the instructions for two different parts to merge, adding it back make things clearer.
> rails setup: add missing newline from markdown

- source/guides/gemfile_ruby.html.md
Feature was implemented in https://github.com/rubygems/rubygems/pull/6876 and documented on the
[manpage](https://bundler.io/v2.5/man/gemfile.5.html#VERSION-required-)
but it seems like it makes sense to have on [this page](https://bundler.io/guides/gemfile_ruby.html) as well, as it is the top google result for "gemfile ruby version".
This copy is lifted (and lightly edited) from the manpage source https://github.com/rubygems/rubygems/blob/6bbc8bed344eeaadcbd8dfcc6e20c9e1eb734d96/bundler/lib/bundler/man/gemfile.5.ronn?plain=1#L72-L80
> Document `file` option for `ruby` directive

- source/compatibility.html.haml
The problem was the end-user who uses Ruby 2.6-3.0 cannot find the installable bundler version on the compatibility page.
Add a description that Bundler 2.5 requires Ruby 3.0.0 and RubyGems 3.2.3.
> Update a compatibility page for Bundler 2.5

- source/blog/2024-12-19-bundler-v2-6.html.markdown
A typo in the recent blog post https://bundler.io/blog/2024/12/19/bundler-v2-6.html made it harder than necessary to try out the new `--add-checksums` feature.
My diagnosis was: it’s a typo.
> Fix typo --add-checkums → --add-checksums

- assets/javascripts/search.js
- assets/stylesheets/application.css.scss
- package-lock.json
- package.json
Bootstarap 5.2.0 (GA) and 5.2.1 was released: https://blog.getbootstrap.com/2022/07/19/bootstrap-5-2-0/ and https://blog.getbootstrap.com/2022/09/07/bootstrap-5-2-1/
Bootstrap 5.2.1 fixed the regression introduced as below in 5.2.0.
~~As of 2022-07-25, Bootstrap 5.2.0 had a regression as below, so we cannot upgrade to 5.2.0. Hopefully we can go with 5.2.1.~~
- https://github.com/twbs/bootstrap/issues/36837
- ~~https://github.com/twbs/bootstrap/issues/36518~~
- https://github.com/twbs/bootstrap/issues/36420
> Bump bootstrap from 5.1.3 to 5.2.0

- Gemfile
- Gemfile.lock
The problem was that a lot of warnings are printed when building and serving the site locally.
I fixed the warnings in upstream gems, and upgraded our Gemfile.
Only one warning is missing, fixed by https://github.com/TwP/servolux/pull/22, but I can't easily point to that PR because that repository does not include a gemspec.
> Upgrade dependencies to fix most warnings

- config.rb
- lib/tasks/versions.rake
- source/guides/getting_started.html.md
- source/whats_new.html.md
The problem was the [getting started page](https://bundler.io/guides/getting_started.html) includes a link to [Bundler 2.4 what's new page](https://bundler.io/v2.4/whats_new.html).
Instead, it should link to the latest version.
My diagnosis was that this page started being missing when it was migrated to HAML in f2c455dd48ee6ea4b9aaf4a8ba0c5528e6658d0d, because we create proxy pages, but only for `.haml` pages:
https://github.com/rubygems/bundler-site/blob/cf57e550ade5164282539fb15676c9d72dd2ce98/config.rb#L49-L58
It was replaced with a hardcoded link to the v2.4 version, which was the latest at the time, but it got out of date.
My fix is to create a symlink like we did in #1424.
I chose this fix because because it's more SEO friendly that a client side redirect.
> Add missing /whats_new.html page

- Gemfile
- Gemfile.lock
- source/contributors.html.haml
- source/layouts/base.haml
- source/layouts/two_column_layout.haml
- source/localizable/index.html.haml
- source/partials/_docs_header.haml
The problem was none. I just wanted to finish the upgrade of all our stack to latest versions.
My fix is to upgrade HAML and take care of a couple of problems that showed up.
Supersedes #918.
> Update to HAML 6

- lib/tasks/vendor_files.rake
The problem was some links in the doc folder imported from rubygems/rubygems were not being properly adapted to the site structure.
My diagnosis was that the regexp to detect relative links not starting with http was incorrect, because it would fail to detect any link with target starting with "h", "t", or "p" as relative.
My fix is to properly use a negative lookahead.
This PR fixes #844. It depends on #1430 since that restore the whole page hierarchy under `/doc`.
> Fix transformation of some relative links

- helpers/docs_helper.rb
- source/layouts/two_column_layout.haml
The problem was that I found several issues with the "Edit this page" links, namely:
* One link was broken after #1426.
* Links in doc pages reintroduced by #1430 were not working, again due to the move of documentation in rubygems/rubygems.
* Links in man pages without version introduced by #1424 were not working either.
* Fix for first issue is to use `!=` haml syntax.
* For the second and third issues, make sure to build links pointing to the new location in rubygems/rubygems.
> Fix several issues with edition links

- lib/tasks/vendor_files.rake
- source/conduct.html.md
- source/guides/bundler_workflow.html.md
- source/guides/gemfile.html.md
- source/guides/gemfile_ruby.html.md
- source/guides/rationale.html.md
- source/guides/rubygems.html.md
- source/guides/rubymotion.html.md
The problem was some content is not searchable.
My fix is to make sure it's indexed by middleman-search by making sure it has a frontmatter title.
Fixes #1241.
> Make sure all searchable pages have a frontmatter title

- Gemfile
- Gemfile.lock
- config.rb
The problem was that some markdown pages are not rendered correctly,
We're using options that are exclusive to that parser, so we should explicitly force it.
My fix is to explicit set the parser that we want.
Before:
After:
I chose this fix because it's the simplest approach. Maybe middleman or kramdown could do better at validating options, but I'm leaving it as is for now.
> Use kramdown GFM parser

- Gemfile
- Gemfile.lock
The problem was none, rather than preferring to point to the main line rather than to a PR. 
Use the latest main branch of middleman.
> Point middleman back to their main branch

- config.rb
The problem was after switching to GFM markdown parser in #1436, our new lines got messed up:
My fix is to restore the previous appearance by passing the specific option to control line wrap behavior:
> Restore new line behavior with GFM parser

- source/guides/gemfile_ruby.html.md
Ruby versions used in guides are mostly archaic.
Upgrade Ruby versions in guide.
> Upgrade Ruby versions in ruby Gemfile guide.

- helpers/config_helper.rb
- source/partials/_commands_sidebar.haml
The problem was that we browsing bundler CLI command documentation, and using the version selector, you'll be redirected to `bundle install` page if the current command is not present in the chosen version.
That is unexpected to me, since the intention when performing that action is to browse the documentation for the same command, but a different version of Bundler.
My fix is only include versions in the selector that have the current command, and to not show the selector at all if the current version is the only one defining the command.
> Improve version selector

- data/known_plugins.yml
There's a potentially useful plugin, but it's not yet listed on the Known Plugins page, making it virtually invisible to the end user.
The plugin was too new to be known and listed.
I added a record to the respective YAML data file.
It's the most straightforward one of all I can think of.
> known plugins: add bundler-versions_report

- source/layouts/two_column_layout.haml
This reverts commit 50063c7691f5ee0cccabe4a58bb97ed748ed5e56.
The problem was that when you google `bundle check`, the first result is https://bundler.io/v2.0/man/bundle-check.1.html. Instead, the first result would be ideally the man page for the latest version, not for a version no longer supported.
My diagnosis was that we should tell google to consider the non versioned URL the canonical page for all versioned ones, so that it always prefer to list that page.
My fix is to revert the commit where I stopped doing this. The rationale was that these pages are not identical to each other, but I think canonical is also appropriate for pages with similar content.
I chose this fix because I'd like to see if has the desired effect.
> Revert "Only add a canonical tag to the latest version of man pages"

- config.rb
The problem was that issues.html page is 404.
My diagnosis was that the issues page was removed from the source repo at https://github.com/rubygems/rubygems/pull/4980.
My fix is to link to the bug report template, since it's the most similar resource that we have.
I chose this fix because it fixes the 404.
> Redirect old issues page to bug report template

- helpers/docs_helper.rb
The problem was that for urls like `https://bundler.io/man/bundle-install.1.html`, version selector is not currently being displayed.
My fix is to make sure all urls received by the helper that finds the documentation page for a version start with `/` and end with `.html`.
I chose this fix because it makes things simpler and more consistent.
> Fix version selector sometimes missing

- helpers/docs_helper.rb
The problem was that the links to commands documentation in https://bundler.io/docs.html got broken after #1457.
My fix is to adapt to the change in the `documentation_path` helpers which expects valid paths starting from "/", and ending with ".html".
> Fix documentation links

- config.rb
- helpers/config_helper.rb
- helpers/docs_helper.rb
- helpers/guides_helper.rb
- source/layouts/two_column_layout.haml
- source/localizable/index.html.haml
- source/partials/_commands_sidebar.haml
The problem was after #1459, commands are no longer properly categorized between "Primary Commands" and "Utilities".
My fix is to make sure url normalization to prepend "/" and append ".html" is applied consistently.
I also added other improvements to favor URLs without a version as much as possible since those are guaranteed to have docs for the latest version every time.
> Fix command categorization

- lib/tasks/vendor_files.rake
https://bundler.io/changelog.html was showing the rubygems changelog instead of the bundler changelog.
The bundler repository was archived and moved to the a rubygems subdirectory, so I guess that the website code was not updated to reflect the change, and continued reading from the root CHANGELOG.
Path changed to point to the right changelog.
I don't see any other options.
After this change:
> Use correct CHANGELOG file

- source/guides/rubygems.html.md
I have found interesting confusion at [rest-client Gemfile](https://github.com/rest-client/rest-client/blob/2c72a2e77e2e87d25ff38feba0cf048d51bd5eca/Gemfile#L3-L7). It tries to load gemspec by filename using `name` argument. I was at first confused why that doesn't work, but I have realized the behaviour is different. Bundler loads all gemspecs at given path and filter them based on name entry in gemspec, not by filename.
Let's update the guides to explain this better.
> Clarify gemspec arguments and behaviour.

- source/localizable/index.html.haml
- got reported it doesn't work anymore, here's new one, sadly only for 30 days
> Update Slack invite link for chat support
