rubygems/bundler-site

- source/v1.7/gemfile.haml
- source/v1.8/gemfile.haml
- source/v1.9/gemfile.haml
It might be typo, is it correct?
> typo(gemfile): from the same same -> from the same

- source/stylesheets/application.scss
@indirect follow the PR without the margin-top.
> Removed unnecessary margin-top from .license

- .gitignore
- Rakefile
> [Rakefile] Treat man pages as normal source

- source/blog/2015-12-12-version-1-11-released.md
> Add 1.11 announcement post

- source/v1.12/whats_new.haml
https://github.com/bundler/bundler/issues/4522
> Fix link to changelog.

- source/v1.12/bundle_config.haml
See bundler/bundler#4186 for implementation.
> Added documentation for mirror.URL.fallback_timeout

- source/v1.12/gemfile_ruby.html.haml
> [Gemfile] Add documentation about `ruby` directive version operators

- config.rb
> Use guides layout for conduct.html

- README.md
Just two style inconsistencies from #238.
> README style

- .travis.yml
- Gemfile
- Gemfile.lock
- lib/tasks/travis/clean_fastly_cache.rake
- lib/tasks/travis/deploy.rake
Even if it fails it should not break deploy :)
Closes #233
> Add fastly cache purge after deploy

- source/blog/2016-09-08-bundler-1-13.html.md
> "brew" => "bundle" doctor and 2 typos

- source/localizable/v1.12/guides/using_bundler_in_application.en.html.md
- source/v1.12/faq.html.md
- source/v1.12/git_bisect.html.md
> Add simple git bisect guide

- source/blog/2016-09-08-bundler-1-13.html.md
sheesh ... details details details ;)
> _three_ experimental features

- source/v1.13/gemfile.html.haml
Related to https://github.com/rubygems/rubygems/issues/896
> Clarify what ~> 0 version constraint means

- source/localizable/v1.13/guides/creating_gem.en.html.md
Some cross-linking to RubyGems guides! I couldn't find a spot to fit in the two links at the top, so I made a small "Related reading" list.
> Cross-link to RubyGems guides.

- source/v1.13/bundler_setup.html.haml
- source/v1.13/bundler_workflow.html.haml
- source/v1.13/docs.html.haml
- source/v1.13/gemfile.html.haml
Hi Again,
Many apologies but i have missed some links in the footer for the Rails pages and have broken them. This PR fixes that broken link and also makes more updates to documentation relating to rails 3.
There are a few more rails 3 things still left to update and ill get around that later.
Thank you!
> fixed breaking rails link and also updated more rails 3 documentation

- source/v1.13/index.html.haml
closes #256
Just a quick note to clarify system requirements! I didn't link to any install guides since bundler is used by so many different operating systems.
Bonus ✨ change: I removed a line break that was making the `:code` formatting have an extra line break (I couldn't not see it omg 😳)
> tiny bit of instructions to clarify system requirements

- .travis.yml
- Gemfile
- Gemfile.lock
> [Travis] Allow building with homu

- source/v1.12/index.html.md
- source/v1.13/index.html.haml
- source/v1.14/index.html.haml
> Fix Getting Started link to bundle_gem man pages

- source/layouts/_favicon.haml
Similar to #288 but fixes the existing tags instead.
> fix favicon links

- lib/tasks/man_generator/man.rake
Want to see if this fixes things on heroku
> [Rakefile] Use bundle exec when calling ronn

- locales/es.yml
- There's no localization of the bundler-site in castillian Spanish.
- I saw that there was no `es.yml` file in the locales directory of the `bundler-site` repo.
My fix...
- I wanted to create the first localized Spanish file! ✨
- I know we don't want to start localization of documentation until we add more explanations to the English dos, but this file seemed like a great first file to localize. It doesn't seem like it will change very much in spite of widespread doc changes.
💙
> Add Spanish locale

- helpers/canonical_helper.rb
- source/layouts/base.haml
- source/layouts/commands_layout.haml
Due to force indexing newest man page to search engine,
add `<link rel="canonical" href="path">` to reference pages.
---
ref: https://github.com/bundler/bundler-site/issues/308
- modify `layouts/base` to add canonical tag when `content_for(:canonical)` is present
- add `content_for(:canonical)` to `layouts/commands_layout`
+ when path is in `{vX.X}/man/` or `{vX/X}/bundle_*/`
+ remove version prefix to point out newest version of documents
```
diff -r build/sitemap.xml build.old/sitemap.xml
5c5
<     <lastmod>2017-06-13T01:03:55Z</lastmod>
---
>     <lastmod>2017-06-12T16:03:54Z</lastmod>
diff -r build/v1.0/man/bundle-config.1.html build.old/v1.0/man/bundle-config.1.html
12d11
<     <link href='/man/bundle-config.1.html' rel='canonical'>
diff -r build/v1.0/man/bundle-exec.1.html …
```
> add canonical tags for commands_layout

- .github/PULL_REQUEST_TEMPLATE.md
There is a typo in the next question...
Wrong word
Fixed with correct word
I couldn't think of another fix.
> Fixed typo in PR template.

- source/localizable/v1.15/guides/bundler_sharing.es.html.haml
- There was a missing Spanish translation for the "Sharing your code" guide.
- There's a lot of missing translations for Bundler documentation
My fix...
- To localize "Sharing your code" into Spanish.
- To spread the awesomeness of Bundler documentation to Spanish-speakers 👌🏼
> Localize Sharing Code Guide into Spanish

- lib/tasks/contributors.rake
Update the `core_team` list to reflect the current team
> Update core_team in the contributors import rake task to reflect the current core team

- source/blog/2018-01-17-making-gem-development-a-little-better.html.markdown
I was asked to write a post on the new gem lock file change and recommendations. @indirect had some suggestions upon reviewing it and now I made some small edits to those suggestions for consistency with rest of post.
@indirect I thought I'd make a PR with the changes I requested upon reviewing your PR - might be easier for you. 😃 You can either add my review changes in PR #358 or just merge this PR as it incorporates both your suggestions and my edits for consistency with rest of article. 
If there's any more changes, let me know, otherwise I think we're good to go.
> Some edits to gem lock post suggestions for consistency.

- source/blog/2018-03-09-february-bundler-update.html.markdown
We're turning the Bundler section of the [Ruby Together Monthly Update](https://rubytogether.org/news) into a blog post on the Bundler blog. This is for the month of Feb.
to write it!
My fix...
...we're trying to surface updates to the Bundler audience :)
> Wrote feb bundler update blog post

- source/v1.16/guides/bundler_in_a_single_file_ruby_script.html.md
- source/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
A user reported a possible problem and fix for reconciling their rubygems certificate in vagrant (https://github.com/rubygems/rubygems/issues/1736#comment-373312394). We wanted to add this to the guide.
Additionally, while testing out the links in staging, I noticed that many of the jump links in the doc weren't properly set, so I made sure the anchor text matched the title of the section.
1. add a possible solution for vagrant users
2. fix the jump links
My fix...
see above!
it would help vagrant users access a possible solution && users would actually be able to jump around the doc …
> Added Vagrant section & fixed jump links

- source/v1.16/guides/bundler_in_a_single_file_ruby_script.html.md
The example code was not copy-and-pastable due to smart quotes.
My diagnosis was that the smart quotes would be syntax errors in Ruby.
My fix was the replace the smart quote marks in the Markdown file.
It seemed easiest.
> Replace smart quotes with quotes

- data/contributors.yml
- source/blog/2018-04-09-march-bundler-update.html.markdown
- source/conduct.html.md
Each month, we're cross-posting monthly updates from Ruby Together on the Bundler blog. I created the new post, based on the updates already published in Ruby Together.
> created march update post

- source/blog/2018-06-07-may-bundler-update.html.markdown
Drafted the May monthly update blog post for the Bundler site! cc @indirect
> Created May monthly update

- helpers/docs_helper.rb
- source/layouts/commands_layout.haml
- source/layouts/guides_layout.haml
- source/layouts/md_guides_layout.haml
- source/stylesheets/application.css.scss
Closes #376 
My fix...
This is hacky and I haven't tested all pages and the CSS needs some work, but I wanted you to be able to try this out @rubymorillo
> Add a link to contribute to the current page

- data/contributors.yml
- source/blog/2018-05-07-april-bundler-monthly-update.html.markdown
April monthly update blog post
> created april monthly update

- source/v1.16/guides/bundler_plugins.html.haml
The problem was a grammar error
My diagnosis was reading the docs and seeing the grammar error.
My fix was to fix the grammar error.
I chose this fix because I read these docs from a link inside of ruby weekly.
> Remove gramatical error

- source/blog/2016-04-28-the-new-index-format-fastly-and-bundler-1-12.html.md
- source/blog/2018-01-08-monthly-update-for-december-and-yearly-update-for-2017.html.markdown
- source/localizable/v1.12/guides/using_bundler_in_applications.en.html.md
- source/localizable/v1.12/guides/using_bundler_in_applications.pl.html.md
- source/localizable/v1.13/guides/using_bundler_in_applications.en.html.md
- source/localizable/v1.13/guides/using_bundler_in_applications.pl.html.md
- source/localizable/v1.14/guides/using_bundler_in_applications.en.html.md
- source/localizable/v1.14/guides/using_bundler_in_applications.pl.html.md
- source/v1.10/index.html.haml
- source/v1.10/whats_new.html.haml
- source/v1.11/index.html.haml
- source/v1.12/gemfile.html.md
- source/v1.13/index.html.haml
- source/v1.14/index.html.haml
- source/v1.15/index.html.haml
- source/v1.16/bundle_install.html.haml
- source/v1.16/guides/bundler_plugins.html.haml
- source/v1.16/index.html.haml
- source/v1.2/index.html.haml
- source/v1.3/index.html.haml
- source/v1.5/index.html.haml
- source/v1.6/index.html.haml
- source/v1.7/index.html.haml
- source/v1.8/index.html.haml
- source/v1.9/index.html.haml
The problem was... broken links on the bundler website
My diagnosis was... mostly incorrect relative URLs.
My fix... use the correct URLs
I chose this fix because... keeps the links working.
fixes #383
> Fixes Broken links

- source/blog/2018-07-12-june-bundler-update.html.markdown
- source/blog/2018-07-13-june-bundler-update.html.markdown
- source/localizable/index.html.haml
I took the Bundler section of the RT monthly update and created the corresponding post for the Bundler blog.
> Created June monthly update blog post

- source/blog/2018-08-10-july-bundler-update.html.markdown
Here's the blog post with July's Bundler updates!
> Created July 2018 update blog post

- source/blog/2018-09-10-august-bundler-update.html.markdown
Created the monthly update blog post for August
> Created August monthly update

- source/v1.16/guides/groups.html.haml
Update to hash syntax pretty much everyone is using these days.
> Switch groups guide to standard hash syntax

- source/v1.16/guides/bundler_setup.html.haml
Update to standard hash syntax pretty much everyone is using.
> Switch setup guide to standard hash syntax

- source/v1.16/guides/bundler_in_a_single_file_ruby_script.html.md
And the gloomy becomes bright and colorful(ish)!
> Add Ruby syntax highlighting

- source/localizable/v1.16/guides/creating_gem.en.html.md
Update to hash syntax pretty much everyone is using.
> Switch creating gem guide to standard hash syntax

- source/javascripts/application.js
- source/javascripts/seedanddew.js
They're trying to put together a system where companies and individuals
fund open source based on how much time each contributor spends looking
at the docs for a specific project. RSpec is also trying this out, and
it seems like it won't cost us anything and might work out well. Let's
find out.
> Tracker to try out seedanddew.com

- source/blog/2018-10-15-september-monthly-update.html.markdown
Blog post with September monthly update information
> September Monthly Update

- Gemfile.lock
The current version of rack contains a few reported vulnerabilities.
Update rack to the latest version
> update rack to the latest version

- source/blog/2018-11-05-october-monthly-update.html.markdown
October monthly update blog post
> October monthly update blog post

- source/blog/2019-01-03-announcing-bundler-2.html.markdown
- source/blog/2019-01-04-an-update-on-the-bundler-2-release.html.markdown
This PR contains the Bundler 2 update blog post.
> post bundler 2 update

- source/blog/2019-02-02-december-monthly-update.html.markdown
Blog post with Dec 2018 recap
My fix...
> Created Dec 2018 monthly update

- source/v1.12/groups.html.md
broken link
missing /v1.12 in url
add /v1.12 to url
simple and effective
> fix link to bundle_config

- source/blog/2019-03-12-january-february-bimonthly-update.html.markdown
- source/blog/2019-03-13-january-february-bimonthly-update.html.markdown
Bundler update blog post for Jan/Feb 2019
> Created Jan and Feb bimonthly Bundler update

- source/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
> Updated the Automated SSL script URL

- source/localizable/index.html.haml
The problem was a broken link. 
My diagnosis was a typo in the source. 
My fix is a `,`. 🎉 
I chose this fix because it was easy and fixes the problem.
> Fix HackerOne link

- source/v1.5/gemfile.html.haml
Some extra 'the' article
Just removed it
> Remove extra 'the' article

- source/v2.0/guides/bundler_setup.html.haml
The problem was an extra comma and an unnecessary article (an) in the documentation.
> Remove extra Comma; Remove Unnecessary Article (an)

- source/v2.0/guides/bundler_sharing.html.haml
> Remove Extra Commas and Sync with rationale.html.haml

- source/v0.9/deploying.html.haml
- source/v0.9/gemfile.html.haml
- source/v0.9/index.html.haml
- source/v1.0/gemfile.html.haml
- source/v1.0/index.html.haml
- source/v1.1/gemfile.html.haml
- source/v1.1/index.html.haml
- source/v1.10/gemfile.html.haml
- source/v1.11/gemfile.html.haml
- source/v1.13/gemfile.html.haml
- source/v1.14/gemfile.html.haml
- source/v1.15/gemfile.html.haml
- source/v1.16/gemfile.html.haml
- source/v1.17/gemfile.html.haml
- source/v1.2/gemfile.html.haml
- source/v1.3/gemfile.html.haml
- source/v1.5/gemfile.html.haml
- source/v1.6/gemfile.html.haml
- source/v1.7/gemfile.html.haml
- source/v1.8/gemfile.html.haml
- source/v1.9/gemfile.html.haml
- source/v2.0/gemfile.html.haml
The problem was that while working on canonical links, I was grepping for "Learn More" links and missing a few expected results.
My diagnosis was that "Learn More" links have inconsistent casing.
My fix is to make it consistent.
I chose this fix because it makes the site's look more uniform and not subject to grepping surprises. I'm also happy with the "Inverse fix" of changing everything to "Learn more".
> Normalize case

- .github/workflows/build.yml
The workflow was not getting triggered when a PR was opened.
The "on pull_request" configuration was missing.
Added the proper configuration.
> Trigger workflow on pull request

- source/blog/2020-04-27-march-monthly-update.html.markdown
Blog post with March 2020 Recap
My fix...
> Create Bundler March Updates

- Gemfile.lock
- includes sass/sassc-ruby#158 which potentially fixes unstable CI
> Update sassc to 2.3.0.

- source/localizable/v2.0/guides/creating_gem.en.html.md
The problem was there seems to be a typo in the documentation.
> Updating creating_gem.en.html.md

- source/blog/2018-11-04-an-update-on-bundler-2.html.markdown
- source/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
- source/v1.17/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
- source/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
Point links to the correct bundler issue tracker
closes rubygems/rubygems#3642
> Link to the correct bundler issue tracker

- source/v2.1/guides/bundler_plugins.html.haml
The plugin guide did not cover these two topics.
See the docs I've written.
Wrote docs.
I'm not aware of other options.
> Plugin docs: mention uninstall & introduce BundlerError and explain how Bundler rescues those

- Gemfile.lock
- README.md
- source/v2.1/bundle_plugin.html.haml
> Reference page for plugin commands

- source/v1.15/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
- source/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
- source/v1.17/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
- source/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
- source/v2.1/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
The problem was that the linked .pem file 404d.
My diagnosis was taken from #540, and impl. here as a tiny change to the 2.1 document.
See #540
My fix is a wording change.
I chose this fix because: the other documents are of... historical value? Perhaps? Perhaps they should also change, now? What do _you_ think?
> SSL troubleshooting: Update .pem link

- app.json
We're using an old heroku stack.
Upgrade the stack. Going through a PR to check with a review app first.
> Upgrade heroku stack to heroku-20

- source/blog/2021-02-15-a-more-secure-bundler-we-fixed-our-source-priorities.html.markdown
We had to revert the change we bragged about :grimacing: 
Not really sure what the best way to handle this kind of situation is. I guess a note at the top of the blog post?
> Add a note about the improvement no longer being there

- source/compatibility.html.haml
The problem was that this page is out of date.
My fix to document our current policy. I don't think we need to document all past compatibility issues here.
> Bring compatibility page up to date

- source/blog/2021-02-15-a-more-secure-bundler-we-fixed-our-source-priorities.html.markdown
The problem was we made some improvements regarding dependency confusion, but didn't update this note.
My fix is to update the note to explain the current situation.
> Update blog post note

- package-lock.json
A github security alert.
Bump tar.
> `npm update tar`

- .github/workflows/deploy.yml
I forgot to bump ruby in the deploy job at #588.
My fix is to bump it.
> Bump ruby in deploy job too

- source/v1.13/gemfile_ruby.html.haml
- source/v1.14/gemfile_ruby.html.haml
- source/v1.15/gemfile_ruby.html.haml
- source/v1.16/gemfile_ruby.html.haml
- source/v1.17/gemfile_ruby.html.haml
- source/v2.0/gemfile_ruby.html.haml
- source/v2.1/gemfile_ruby.html.haml
- source/v2.2/gemfile_ruby.html.haml
The problem was a broken link
My diagnosis was a new version of the page was created but no redirect exists
My fix changing the link
I chose this fix because it fixes the link
> Fix broken link

- data/known_plugins.yml
- source/v1.16/guides/bundler_plugins.html.haml
- source/v1.17/guides/bundler_plugins.html.haml
- source/v2.0/guides/bundler_plugins.html.haml
- source/v2.1/guides/bundler_plugins.html.haml
- source/v2.2/guides/bundler_plugins.html.haml
The original owner most likely deleted their profile on github
> Remove outdated link for bundle command

- .github/workflows/build.yml
- Gemfile.lock
- README.md
- package-lock.json
- package.json
The problem was none. Just keeping things up to date.
`npm update` and others.
> Update some dependencies

- source/layouts/base.haml
fixes https://github.com/rubygems/bundler-site/pull/371
> add meta tag for specifying language

- app.json
Nothing really, just a heroku deployment warning.
My fix is to upgrade to the new stack as suggested by Heroku.
> Upgrade stack to heroku-22

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- Update actions/checkout from v1 to v3
- Update actions/setup-node from v1/v2 to v3
- Update Node.js from 15 to 16 in deploy job
> Update GitHub Actions templates

- source/layouts/compatibility_layout.haml
Layouts are too many for this site.
Remove layout(s) no more used.
Remove the layout unused after sponsor showcase removal in #558.
- cf. #647
> Remove unused compatibility_layout

- source/guides/gemfile.html.haml
- source/guides/gemfile_ruby.html.haml
Some relative links are dead after #671.
Relative URLs should be updated.
Relative URLs were updated.
n/a 
> Update static links after PR 671

- package-lock.json
- package.json
> Remove jQuery dependency

- source/localizable/index.html.haml
https://web.dev/optimize-cls/
Cumulative Layout Shift (CLS) would be increased while it is currently 0.37.
Will be pasted when this is deployed (in my test env it is 0).
> Optimize cumulative layout shift (CLS) on top page

- locales/en.yml
- locales/es.yml
- locales/pl.yml
- source/layouts/_footer.haml
- source/localizable/about.en.html.haml
Closes #716
n/a
- Add /about.html with i18n.
- Add a link to the about in footer.
> Add /about.html

- package-lock.json
> Completely remove node-sass from package-lock.json

- .github/workflows/deploy.yml
- lib/tasks/ci/deploy.rake
> Correct git config on Git commit on deploy task

- source/guides/getting_started.html.haml
> Fix internal links from Getting Started

- .haml-lint.yml
- source/guides/getting_started.html.haml
- source/layouts/_navbar.haml
- source/layouts/two_column_layout.haml
> Enable ClassesBeforeIds entirely in HAML-Lint

- .haml-lint.yml
- .rubocop.yml
> Enable Style/StringLiterals in RuboCop

- .github/workflows/deploy.yml
Closes #744
Fixes up #241
cf.
- #233
- #339
- #558
> Remove CDN purge command from deploy job

- .github/workflows/build.yml
- .github/workflows/test.yml
Set permisions to Actions workflows to make jobs secure.
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
> Set permisions to Actions workflows

- assets/javascripts/anchors.js
- assets/javascripts/two_column_layout.js
- source/layouts/two_column_layout.haml
- webpack.config.js
> Remove useless anchors from sidebar

- source/robots.txt
> Use HTTPS in robots.txt

- source/localizable/about.en.html.haml
Per completion of #591, docs should be updated.
Follows up #789
Updates #717
> Update docs about architecture

- .rubocop.yml
- Gemfile
> Annotate entries in Gemfile with sorting

- .github/workflows/deploy.yml
- config.rb
Partially reverts #795
Closes #814
> Use path in actions/upload-pages-artifact

- config.rb
> Avoid dead links by creating weird pages

- .rubocop.yml
- Gemfile
- config.rb
- config.ru
- helpers/command_reference_helper.rb
- helpers/docs_helper.rb
- helpers/guides_helper.rb
- lib/tasks/man_generator/man.rake
- lib/tasks/man_generator/strip_pages.rake
- lib/tasks/regenerate_known_plugins_yml.rake
- lib/tasks/vendor_files.rake
- lib/tasks/versions.rake
- source/sitemap.xml.builder
> Enforce Style/StringLiterals cop

- config.rb
> Redirect /team to /contributors

- source/v1.12/bundle_version.html.md
- source/v1.13/bundle_version.html.haml
- source/v1.14/bundle_version.html.haml
- source/v1.15/bundle_version.html.haml
- source/v1.16/bundle_version.html.haml
- source/v1.17/bundle_version.html.haml
- source/v2.0/bundle_version.html.haml
- source/v2.1/bundle_version.html.haml
- source/v2.2/bundle_version.html.haml
- source/v2.3/bundle_version.html.haml
> Use h1 in bundle version

- .haml-lint.yml
- source/guides/bundler_plugins.html.haml
- source/guides/deploying.html.haml
- source/guides/gemfile.html.haml
- source/guides/gemfile_ruby.html.haml
- source/guides/getting_started.html.haml
- source/guides/rubygems.html.haml
- source/layouts/_navbar.haml
- source/localizable/about.en.html.haml
- source/localizable/index.html.haml
- source/v1.12/whats_new.html.haml
- source/v1.13/whats_new.html.haml
- source/v1.14/whats_new.html.haml
- source/v1.15/guides/deploying.html.haml
- source/v1.16/whats_new.html.haml
- source/v1.17/whats_new.html.haml
- Follows up #776
- Blocks #924
> Set max value for LineLength in HAML-Lint linter

- data/contributors.yml
- lib/tasks/contributors.rake
The problem was none, just making sure our contributors list is up to date.
My fix is to run `bin/rake contributors:update` and commit the result. I also documented this task so that it appears under `bin/rake -T`.
> Update contributors list

- lib/versions.rb
Closes #769
This repo should use state-of-the-art Ruby syntax (2.7).
> Use the numbered parameters in calculating VERSIONS

- source/blog/2016-04-28-the-new-index-format-fastly-and-bundler-1-12.html.md
- source/blog/2016-09-08-bundler-1-13.html.md
- source/blog/2017-03-28-bundler-1-14-so-many-fixes.html.markdown
- source/v1.12/whats_new.html.haml
https://www.ssllabs.com/ssltest/analyze.html?d=andre.arko.net&latest
- Part of #1001
> Use https in links to andre.arko.net

- Gemfile
- Gemfile.lock
We cannot use Haml 6.
middleman we used to use did not support Haml 6 at that moment.
Update middleman (unreleased) to the latest.
Try https://github.com/middleman/middleman/pull/2588 first.
> Update middleman from 038f4f60 to 50f76c29

- package-lock.json
browserslist is depended only by `webpack`.
> Update browserslist from 4.18.1 to 4.21.4

- package-lock.json
https://github.com/postcss/postcss/releases/tag/8.4.20
> Update postcss from 8.4.19 to 8.4.20

- source/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
- source/v1.15/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
> Update dead links to Fastly with the new one

- source/blog/2017-03-28-bundler-1-14-so-many-fixes.html.markdown
- source/blog/2018-01-17-making-gem-development-a-little-better.html.markdown
- source/blog/2018-09-10-august-bundler-update.html.markdown
- source/localizable/guides/creating_gem.en.html.md
- source/localizable/guides/creating_gem.pl.html.md
Part of #1001
https://www.ssllabs.com/ssltest/analyze.html?d=github.com&latest
> Use https in links to github.com

- Gemfile.lock
https://github.com/monora/rgl/releases/tag/v0.5.10
> Update rgl from 0.5.9 to 0.5.10

- Gemfile
- Gemfile.lock
> Good bye, Pry: replace it with irb

- source/guides/getting_started.html.md
Syntactical error present in code sample for the example gemfile used in the getting started section of the guides.
It was merely a typo.
My fix...
Was to replace the syntax errors `](` with the proper syntax of `', '`
Not really any other options 🤷‍♂️😅
> fix syntax for rack specification line

- source/v2.4/whats_new.html.md
The problem was the broken link to the blog article
My diagnosis was that the link was wrong
My fix is to use the right url
I chose this fix because it's the right one
> fix link to blog article

- source/blog/2014-08-14-bundler-may-install-gems-from-a-different-source-than-expected-cve-2013-0334.html.markdown
- source/blog/2023-01-31-bundler-v2-4.html.markdown
Bad formatting in blog posts.
My diagnosis was language marker in fenced code blocks does not seem to work.
Remove it.
> Remove language marker in fenced code blocks

- .github/PULL_REQUEST_TEMPLATE.md
If someone does not remove this section, the ticket is more difficult to scan.
The problem was that editing Pull Requests can be fiddly and you want to avoid confusing the reader. The pr author opts to fill in only what they know, ignoring the rest. 
The template text in the beginning is not one of those "fill in the blanks" that the others are. 
My diagnosis was that some users leave that text section unedited, making their text read worse. 
My fix is to wrap only that section in an HTML comment, hiding it from view.
I chose this fix for the initial paragraph only because the other sections read more like sentences to complete.
> Comment around initial section

- source/compatibility.html.haml
The problem was that I believe if the information is given split in two different sections, the policy becomes harder to understand.
My diagnosis was that it would be more clear if both sections are merged.
My fix is to merge both sections.
> Tweak compatibility page

- .haml-lint.yml
- source/contributors.html.haml
- source/layouts/base.haml
- source/layouts/two_column_layout.haml
- source/localizable/index.html.haml
- source/partials/_blog_header.haml
- source/v1.12/docs.html.haml
- source/v1.13/docs.html.haml
- source/v1.14/docs.html.haml
- source/v1.15/docs.html.haml
- source/v1.16/docs.html.haml
- source/v1.17/docs.html.haml
- source/v2.0/docs.html.haml
- source/v2.1/docs.html.haml
- source/v2.2/docs.html.haml
- source/v2.3/docs.html.haml
- source/v2.4/docs.html.haml
The PR that updates haml-lint fails its lint step. #1176 
Perhaps haml-lint's rules evolved to take more details into account.
More RuboCop rules.
This PR makes haml-lint pass without failures.
- follow some of the rules
- disable one rule, which kind of does not make sense in HAML
It was quick.
> Haml lint fix

- source/layouts/two_column_layout.haml
None, this is a refactoring.
My diagnosis was we are not using the captures for anything, so we could use `#match?` here, which only returns a boolean.
My fix is to change the implementation.
I chose this fix because it's efficient.
> Refactor to use #match?

- source/v1.12/docs.html.haml
- source/v1.13/docs.html.haml
- source/v1.14/docs.html.haml
- source/v1.15/docs.html.haml
- source/v1.16/docs.html.haml
- source/v1.17/docs.html.haml
- source/v2.0/docs.html.haml
- source/v2.1/docs.html.haml
- source/v2.2/docs.html.haml
- source/v2.3/docs.html.haml
- source/v2.4/docs.html.haml
- source/v2.5/docs.html.haml
The problem was I noticed this typo while working on Bundler 2.6 updates.
My fix is to remove the duplicated word.
> Fix duplicated "and"

- .github/workflows/deploy.yml
The problem was that I renamed the default branch to main as per #1441, but the deploy workflow needs to be updated.
My fix to use the new name in the workflow.
Closes #1441.
> Update default branch in deploy workflow to main

- source/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
The problem was that I was about to change a link to point to our brand new "main" branch, but I realized the whole section is unnecessary.
My diagnosis was that our site has consistent links on every footer to the source code for contributing, so this is essentially duplicated.
My fix is to remove the section.
> Remove unnecessary guide section

- source/conduct.html.md
The problem was the email contact in CoC is not clickable.
My fix is to make it clickable, catching up with Catch up with https://github.com/rubygems/rubygems/pull/8849.
> Make CoC clickable
